/** Sourced from https://github.com/davejt/exercise/edit/master/data/exercises */
const exerciseData = [
  { name: "Barbell Bench Press", bodyPart: "Chest" },
  { name: "Barbell Squat", bodyPart: "Quadriceps" },
  { name: "Barbell Deadlift", bodyPart: "Lower Back" },
  { name: "Bent Over Barbell Row", bodyPart: "Middle Back" },
  { name: "Chin-Up", bodyPart: "Lats" },
  { name: "Dumbbell Bicep Curl", bodyPart: "Biceps" },
  { name: "Ez-Bar Curl", bodyPart: "Biceps" },
  { name: "Seated Calf Raise", bodyPart: "Calves" },
  { name: "Sit-Up", bodyPart: "Abdominals" },
  { name: "Sumo Deadlift", bodyPart: "Hamstrings" },
  { name: "Lat Pulldown", bodyPart: "Lats" },
  { name: "Ez-Bar Skullcrusher", bodyPart: "Triceps" },
  { name: "Arnold Dumbbell Press", bodyPart: "Shoulders" },
  { name: "Face Pull", bodyPart: "Shoulders" },
  { name: "Farmers Walk", bodyPart: "Forearms" },
  { name: "Barbell Hip Thrust", bodyPart: "Glutes" },
  { name: "Dumbbell Shrug", bodyPart: "Traps" },
  { name: "Pullups", bodyPart: "Lats" },
  { name: "Leg Press", bodyPart: "Quadriceps" },
  { name: "Romanian Deadlift", bodyPart: "Hamstrings" },
  // Finish visible exercises by default
  { name: "Ab Crunch Machine", bodyPart: "Abdominals" },
  { name: "Ab Roller", bodyPart: "Abdominals" },
  { name: "Adductor", bodyPart: "Adductors" },
  { name: "Air Bike", bodyPart: "Abdominals" },
  { name: "Alternate Heel Touchers", bodyPart: "Abdominals" },
  { name: "Axle Deadlift", bodyPart: "Lower Back" },
  { name: "Advanced Kettlebell Windmill", bodyPart: "Abdominals" },
  { name: "Band Assisted Pull-Up", bodyPart: "Lats" },
  { name: "Barbell Ab Rollout", bodyPart: "Abdominals" },
  { name: "Barbell Curl", bodyPart: "Biceps" },
  { name: "Barbell Curls Lying Against An Incline", bodyPart: "Biceps" },
  { name: "Barbell Full Squat", bodyPart: "Quadriceps" },
  { name: "Barbell Glute Bridge", bodyPart: "Glutes" },
  { name: "Barbell Incline Bench Press - Medium Grip", bodyPart: "Chest" },
  { name: "Barbell Incline Shoulder Raise", bodyPart: "Shoulders" },
  { name: "Barbell Lunge", bodyPart: "Quadriceps" },
  { name: "Barbell Rear Delt Row", bodyPart: "Shoulders" },
  { name: "Barbell Shoulder Press", bodyPart: "Shoulders" },
  { name: "Barbell Shrug", bodyPart: "Traps" },
  { name: "Barbell Side Bend", bodyPart: "Abdominals" },
  { name: "Barbell Step Ups", bodyPart: "Quadriceps" },
  { name: "Battling Ropes", bodyPart: "Shoulders" },
  { name: "Bench Dips", bodyPart: "Triceps" },
  { name: "Bent Over Two-Dumbbell Row", bodyPart: "Middle Back" },
  { name: "Bent-Arm Barbell Pullover", bodyPart: "Lats" },
  { name: "Bent-Arm Dumbbell Pullover", bodyPart: "Chest" },
  { name: "Bodyweight Squat", bodyPart: "Quadriceps" },
  { name: "Cable Chest Press", bodyPart: "Chest" },
  { name: "Cable Crossover", bodyPart: "Chest" },
  { name: "Cable Crunch", bodyPart: "Abdominals" },
  { name: "Cable Hammer Curls - Rope Attachment", bodyPart: "Biceps" },
  { name: "Cable Hip Adduction", bodyPart: "Quadriceps" },
  { name: "Cable Incline Pushdown", bodyPart: "Lats" },
  { name: "Cable Incline Triceps Extension", bodyPart: "Triceps" },
  { name: "Cable Internal Rotation", bodyPart: "Shoulders" },
  { name: "Cable Iron Cross", bodyPart: "Chest" },
  { name: "Cable Lying Triceps Extension", bodyPart: "Triceps" },
  { name: "Cable One Arm Tricep Extension", bodyPart: "Triceps" },
  { name: "Cable Preacher Curl", bodyPart: "Biceps" },
  { name: "Cable Rear Delt Fly", bodyPart: "Shoulders" },
  { name: "Cable Reverse Crunch", bodyPart: "Abdominals" },
  { name: "Cable Rope Overhead Triceps Extension", bodyPart: "Triceps" },
  { name: "Cable Rope Rear-Delt Rows", bodyPart: "Shoulders" },
  { name: "Cable Russian Twists", bodyPart: "Abdominals" },
  { name: "Cable Seated Crunch", bodyPart: "Abdominals" },
  { name: "Cable Seated Lateral Raise", bodyPart: "Shoulders" },
  { name: "Cable Shoulder Press", bodyPart: "Shoulders" },
  { name: "Cable Wrist Curl", bodyPart: "Forearms" },
  { name: "Calf Press", bodyPart: "Calves" },
  { name: "Calf Press On The Leg Press Machine", bodyPart: "Calves" },
  { name: "Car Drivers", bodyPart: "Shoulders" },
  { name: "Clean", bodyPart: "Hamstrings" },
  { name: "Clean And Jerk", bodyPart: "Shoulders" },
  { name: "Clean And Press", bodyPart: "Shoulders" },
  { name: "Clean Deadlift", bodyPart: "Hamstrings" },
  { name: "Clean From Blocks", bodyPart: "Quadriceps" },
  { name: "Clean Pull", bodyPart: "Quadriceps" },
  { name: "Clean Shrug", bodyPart: "Traps" },
  { name: "Close-Grip Barbell Bench Press", bodyPart: "Triceps" },
  { name: "Close-Grip Dumbbell Press", bodyPart: "Triceps" },
  { name: "Close-Grip Ez Bar Curl", bodyPart: "Biceps" },
  { name: "Close-Grip Ez-Bar Press", bodyPart: "Triceps" },
  { name: "Close-Grip Front Lat Pulldown", bodyPart: "Lats" },
  { name: "Close-Grip Standing Barbell Curl", bodyPart: "Biceps" },
  { name: "Cocoons", bodyPart: "Abdominals" },
  { name: "Conans Wheel", bodyPart: "Quadriceps" },
  { name: "Concentration Curls", bodyPart: "Biceps" },
  { name: "Cross Body Hammer Curl", bodyPart: "Biceps" },
  { name: "Cross Over - With Bands", bodyPart: "Chest" },
  { name: "Cross-Body Crunch", bodyPart: "Abdominals" },
  { name: "Crossover Reverse Lunge", bodyPart: "Lower Back" },
  { name: "Crunches", bodyPart: "Abdominals" },
  { name: "Cuban Press", bodyPart: "Shoulders" },
  { name: "Deadlift With Bands", bodyPart: "Lower Back" },
  { name: "Deadlift With Chains", bodyPart: "Lower Back" },
  { name: "Decline Barbell Bench Press", bodyPart: "Chest" },
  { name: "Decline Close-Grip Bench To Skull Crusher", bodyPart: "Triceps" },
  { name: "Decline Crunch", bodyPart: "Abdominals" },
  { name: "Decline Dumbbell Bench Press", bodyPart: "Chest" },
  { name: "Decline Dumbbell Flyes", bodyPart: "Chest" },
  { name: "Decline Dumbbell Triceps Extension", bodyPart: "Triceps" },
  { name: "Decline Ez Bar Triceps Extension", bodyPart: "Triceps" },
  { name: "Decline Oblique Crunch", bodyPart: "Abdominals" },
  { name: "Decline Push-Up", bodyPart: "Chest" },
  { name: "Decline Reverse Crunch", bodyPart: "Abdominals" },
  { name: "Decline Smith Press", bodyPart: "Chest" },
  { name: "Deficit Deadlift", bodyPart: "Lower Back" },
  { name: "Depth Jump Leap", bodyPart: "Quadriceps" },
  { name: "Dip Machine", bodyPart: "Triceps" },
  { name: "Dips - Chest Version", bodyPart: "Chest" },
  { name: "Dips - Triceps Version", bodyPart: "Triceps" },
  { name: "Dumbbell Bench Press", bodyPart: "Chest" },
  { name: "Dumbbell Clean", bodyPart: "Hamstrings" },
  { name: "Dumbbell Flyes", bodyPart: "Chest" },
  { name: "Dumbbell Incline Row", bodyPart: "Middle Back" },
  { name: "Dumbbell Incline Shoulder Raise", bodyPart: "Shoulders" },
  { name: "Dumbbell Lunges", bodyPart: "Quadriceps" },
  { name: "Dumbbell Lying One-Arm Rear Lateral Raise", bodyPart: "Shoulders" },
  { name: "Dumbbell Lying Pronation", bodyPart: "Forearms" },
  { name: "Dumbbell Lying Rear Lateral Raise", bodyPart: "Shoulders" },
  { name: "Dumbbell Lying Supination", bodyPart: "Forearms" },
  { name: "Dumbbell One-Arm Shoulder Press", bodyPart: "Shoulders" },
  { name: "Dumbbell One-Arm Triceps Extension", bodyPart: "Triceps" },
  { name: "Dumbbell One-Arm Upright Row", bodyPart: "Shoulders" },
  { name: "Dumbbell Raise", bodyPart: "Shoulders" },
  { name: "Dumbbell Rear Lunge", bodyPart: "Quadriceps" },
  { name: "Dumbbell Scaption", bodyPart: "Shoulders" },
  { name: "Dumbbell Seated Box Jump", bodyPart: "Quadriceps" },
  { name: "Dumbbell Seated One-Leg Calf Raise", bodyPart: "Calves" },
  { name: "Dumbbell Shoulder Press", bodyPart: "Shoulders" },
  { name: "Dumbbell Side Bend", bodyPart: "Abdominals" },
  { name: "Dumbbell Squat", bodyPart: "Quadriceps" },
  { name: "Dumbbell Tricep Extension -Pronated Grip", bodyPart: "Triceps" },
  { name: "Elevated Cable Rows", bodyPart: "Lats" },
  { name: "Elliptical Trainer", bodyPart: "Quadriceps" },
  { name: "Exercise Ball Crunch", bodyPart: "Abdominals" },
  { name: "Exercise Ball Pull-In", bodyPart: "Abdominals" },
  { name: "Flat Bench Cable Flyes", bodyPart: "Chest" },
  { name: "Flat Bench Lying Leg Raise", bodyPart: "Abdominals" },
  { name: "Frankenstein Squat", bodyPart: "Quadriceps" },
  { name: "Freehand Jump Squat", bodyPart: "Quadriceps" },
  { name: "Frog Hops", bodyPart: "Quadriceps" },
  { name: "Front Barbell Squat", bodyPart: "Quadriceps" },
  { name: "Front Barbell Squat To A Bench", bodyPart: "Quadriceps" },
  { name: "Front Box Jump", bodyPart: "Hamstrings" },
  { name: "Front Cable Raise", bodyPart: "Shoulders" },
  { name: "Front Cone Hops (Or Hurdle Hops)", bodyPart: "Quadriceps" },
  { name: "Front Dumbbell Raise", bodyPart: "Shoulders" },
  { name: "Front Incline Dumbbell Raise", bodyPart: "Shoulders" },
  { name: "Front Leg Raises", bodyPart: "Hamstrings" },
  { name: "Front Plate Raise", bodyPart: "Shoulders" },
  { name: "Front Raise And Pullover", bodyPart: "Chest" },
  { name: "Front Squat (Clean Grip)", bodyPart: "Quadriceps" },
  { name: "Front Squats With Two Kettlebells", bodyPart: "Quadriceps" },
  { name: "Front Two-Dumbbell Raise", bodyPart: "Shoulders" },
  { name: "Glute Ham Raise", bodyPart: "Hamstrings" },
  { name: "Glute Kickback", bodyPart: "Glutes" },
  { name: "Goblet Squat", bodyPart: "Quadriceps" },
  { name: "Good Morning", bodyPart: "Hamstrings" },
  { name: "Hack Squat", bodyPart: "Quadriceps" },
  { name: "Hammer Curls", bodyPart: "Biceps" },
  { name: "Hammer Grip Incline Db Bench Press", bodyPart: "Chest" },
  { name: "Hamstring Stretch", bodyPart: "Hamstrings" },
  { name: "Handstand Push-Ups", bodyPart: "Shoulders" },
  { name: "Hang Clean", bodyPart: "Quadriceps" },
  { name: "Hang Snatch", bodyPart: "Hamstrings" },
  { name: "Hanging Leg Raise", bodyPart: "Abdominals" },
  { name: "Hanging Pike", bodyPart: "Abdominals" },
  { name: "Hyperextensions (Back Extensions)", bodyPart: "Lower Back" },
  { name: "Incline Barbell Triceps Extension", bodyPart: "Triceps" },
  { name: "Incline Bench Pull", bodyPart: "Middle Back" },
  { name: "Incline Cable Chest Press", bodyPart: "Chest" },
  { name: "Incline Cable Flye", bodyPart: "Chest" },
  { name: "Incline Dumbbell Curl", bodyPart: "Biceps" },
  { name: "Incline Dumbbell Flyes", bodyPart: "Chest" },
  { name: "Incline Dumbbell Press", bodyPart: "Chest" },
  { name: "Incline Hammer Curls", bodyPart: "Biceps" },
  { name: "Incline Push-Up", bodyPart: "Chest" },
  { name: "Inverted Row", bodyPart: "Middle Back" },
  { name: "Leg Extensions", bodyPart: "Quadriceps" },
  { name: "Leg Lift", bodyPart: "Glutes" },
  { name: "Leg Pull-In", bodyPart: "Abdominals" },
  { name: "Lying Cable Curl", bodyPart: "Biceps" },
  { name: "Lying Dumbbell Tricep Extension", bodyPart: "Triceps" },
  { name: "Lying Leg Curls", bodyPart: "Hamstrings" },
  { name: "Lying Machine Squat", bodyPart: "Quadriceps" },
  { name: "Lying Rear Delt Raise", bodyPart: "Shoulders" },
  { name: "Lying T-Bar Row", bodyPart: "Middle Back" },
  { name: "Lying Triceps Press", bodyPart: "Triceps" },
  { name: "Machine Bench Press", bodyPart: "Chest" },
  { name: "Machine Bicep Curl", bodyPart: "Biceps" },
  { name: "Machine Preacher Curls", bodyPart: "Biceps" },
  { name: "Machine Shoulder (Military) Press", bodyPart: "Shoulders" },
  { name: "Machine Triceps Extension", bodyPart: "Triceps" },
  { name: "Medicine Ball Chest Pass", bodyPart: "Chest" },
  { name: "Medicine Ball Full Twist", bodyPart: "Abdominals" },
  { name: "Medicine Ball Scoop Throw", bodyPart: "Shoulders" },
  { name: "Muscle Snatch", bodyPart: "Hamstrings" },
  { name: "Muscle Up", bodyPart: "Lats" },
  { name: "Neck Press", bodyPart: "Chest" },
  { name: "Oblique Crunches", bodyPart: "Abdominals" },
  { name: "Olympic Squat", bodyPart: "Quadriceps" },
  { name: "One-Legged Cable Kickback", bodyPart: "Glutes" },
  { name: "Overhead Cable Curl", bodyPart: "Biceps" },
  { name: "Overhead Lat", bodyPart: "Lats" },
  { name: "Overhead Squat", bodyPart: "Quadriceps" },
  { name: "Overhead Stretch", bodyPart: "Abdominals" },
  { name: "Overhead Triceps", bodyPart: "Triceps" },
  { name: "Plank", bodyPart: "Abdominals" },
  { name: "Plank With Twist", bodyPart: "" },
  { name: "Plate Pinch", bodyPart: "Forearms" },
  { name: "Plate Twist", bodyPart: "Abdominals" },
  { name: "Platform Hamstring Slides", bodyPart: "Hamstrings" },
  { name: "Plie Dumbbell Squat", bodyPart: "Quadriceps" },
  { name: "Plyo Kettlebell Pushups", bodyPart: "Chest" },
  { name: "Plyo Push-Up", bodyPart: "Chest" },
  { name: "Posterior Tibialis Stretch", bodyPart: "Calves" },
  { name: "Power Clean", bodyPart: "Hamstrings" },
  { name: "Power Jerk", bodyPart: "Quadriceps" },
  { name: "Power Partials", bodyPart: "Shoulders" },
  { name: "Power Snatch", bodyPart: "Hamstrings" },
  { name: "Power Stairs", bodyPart: "Hamstrings" },
  { name: "Preacher Curl", bodyPart: "Biceps" },
  { name: "Preacher Hammer Dumbbell Curl", bodyPart: "Biceps" },
  { name: "Press Sit-Up", bodyPart: "Abdominals" },
  { name: "Pull Through", bodyPart: "Glutes" },
  { name: "Push Press", bodyPart: "Shoulders" },
  { name: "Push Up To Side Plank", bodyPart: "Chest" },
  { name: "Push-Up Wide", bodyPart: "Chest" },
  { name: "Pushups", bodyPart: "Chest" },
  { name: "Pyramid", bodyPart: "Lower Back" },
  { name: "Rack Pulls", bodyPart: "Lower Back" },
  { name: "Rear Leg Raises", bodyPart: "Quadriceps" },
  { name: "Rope Climb", bodyPart: "Lats" },
  { name: "Rope Crunch", bodyPart: "Abdominals" },
  { name: "Rope Jumping", bodyPart: "Quadriceps" },
  { name: "Rope Straight-Arm Pulldown", bodyPart: "Lats" },
  { name: "Rowing", bodyPart: "Back" },
  { name: "Running", bodyPart: "Treadmill" },
  { name: "Russian Twist", bodyPart: "Abdominals" },
  { name: "Sandbag Load", bodyPart: "Quadriceps" },
  { name: "Seated Barbell Military Press", bodyPart: "Shoulders" },
  { name: "Seated Cable Rows", bodyPart: "Middle Back" },
  { name: "Seated Calf Stretch", bodyPart: "Calves" },
  { name: "Seated Dumbbell Curl", bodyPart: "Biceps" },
  { name: "Seated Dumbbell Press", bodyPart: "Shoulders" },
  { name: "Seated Good Mornings", bodyPart: "Lower Back" },
  { name: "Seated Head Harness Neck Resistance", bodyPart: "Neck" },
  { name: "Seated Leg Curl", bodyPart: "Hamstrings" },
  { name: "Seated Leg Tucks", bodyPart: "Abdominals" },
  { name: "Seated One-Arm Cable Pulley Rows", bodyPart: "Middle Back" },
  {
    name: "Seated One-Arm Dumbbell Palms-Down Wrist Curl",
    bodyPart: "Forearms",
  },
  { name: "Seated One-Arm Dumbbell Palms-Up Wrist Curl", bodyPart: "Forearms" },
  { name: "Seated Overhead Stretch", bodyPart: "Abdominals" },
  { name: "Seated Palm-Up Barbell Wrist Curl", bodyPart: "Forearms" },
  { name: "Seated Palms-Down Barbell Wrist Curl", bodyPart: "Forearms" },
  { name: "Seated Side Lateral Raise", bodyPart: "Shoulders" },
  { name: "Seated Triceps Press", bodyPart: "Triceps" },
  {
    name: "Seated Two-Arm Palms-Up Low-Pulley Wrist Curl",
    bodyPart: "Forearms",
  },
  { name: "See-Saw Press (Alternating Side Press)", bodyPart: "Shoulders" },
  { name: "Shotgun Row", bodyPart: "Lats" },
  { name: "Shoulder Circles", bodyPart: "Shoulders" },
  { name: "Shoulder Press - With Bands", bodyPart: "Shoulders" },
  { name: "Shoulder Raise", bodyPart: "Shoulders" },
  { name: "Shoulder Stretch", bodyPart: "Shoulders" },
  { name: "Side Bridge", bodyPart: "Abdominals" },
  { name: "Side Hop-Sprint", bodyPart: "Quadriceps" },
  { name: "Side Jackknife", bodyPart: "Abdominals" },
  { name: "Side Lateral Raise", bodyPart: "Shoulders" },
  { name: "Side Laterals To Front Raise", bodyPart: "Shoulders" },
  { name: "Side Leg Raises", bodyPart: "Adductors" },
  { name: "Side Lying Groin Stretch", bodyPart: "Adductors" },
  { name: "Side Neck Stretch", bodyPart: "Neck" },
  { name: "Side Standing Long Jump", bodyPart: "Quadriceps" },
  { name: "Side To Side Box Shuffle", bodyPart: "Quadriceps" },
  { name: "Side To Side Chins", bodyPart: "Lats" },
  { name: "Side Wrist Pull", bodyPart: "Shoulders" },
  { name: "Side-Lying Floor Stretch", bodyPart: "Lats" },
  { name: "Single Dumbbell Raise", bodyPart: "Shoulders" },
  { name: "Single Leg Butt Kick", bodyPart: "Quadriceps" },
  { name: "Single Leg Glute Bridge", bodyPart: "Glutes" },
  { name: "Single Leg Push-Off", bodyPart: "Quadriceps" },
  { name: "Single-Arm Cable Crossover", bodyPart: "Chest" },
  { name: "Single-Arm Linear Jammer", bodyPart: "Shoulders" },
  { name: "Single-Arm Push-Up", bodyPart: "Chest" },
  { name: "Single-Cone Sprint Drill", bodyPart: "Quadriceps" },
  { name: "Single-Leg High Box Squat", bodyPart: "Quadriceps" },
  { name: "Single-Leg Hop Progression", bodyPart: "Quadriceps" },
  { name: "Single-Leg Lateral Hop", bodyPart: "Quadriceps" },
  { name: "Single-Leg Leg Extension", bodyPart: "Quadriceps" },
  { name: "Single-Leg Stride Jump", bodyPart: "Quadriceps" },
  { name: "Sit Squats", bodyPart: "Quadriceps" },
  { name: "Skating", bodyPart: "Quadriceps" },
  { name: "Sled Drag - Harness", bodyPart: "Quadriceps" },
  { name: "Sled Overhead Backward Walk", bodyPart: "Shoulders" },
  { name: "Sled Overhead Triceps Extension", bodyPart: "Triceps" },
  { name: "Sled Push", bodyPart: "Quadriceps" },
  { name: "Sled Reverse Flye", bodyPart: "Shoulders" },
  { name: "Sled Row", bodyPart: "Middle Back" },
  { name: "Sledgehammer Swings", bodyPart: "Abdominals" },
  { name: "Smith Incline Shoulder Raise", bodyPart: "Shoulders" },
  { name: "Smith Machine Behind The Back Shrug", bodyPart: "Traps" },
  { name: "Smith Machine Bench Press", bodyPart: "Chest" },
  { name: "Smith Machine Bent Over Row", bodyPart: "Middle Back" },
  { name: "Smith Machine Calf Raise", bodyPart: "Calves" },
  { name: "Smith Machine Close-Grip Bench Press", bodyPart: "Triceps" },
  { name: "Smith Machine Decline Press", bodyPart: "Chest" },
  { name: "Smith Machine Hang Power Clean", bodyPart: "Hamstrings" },
  { name: "Smith Machine Hip Raise", bodyPart: "Abdominals" },
  { name: "Smith Machine Incline Bench Press", bodyPart: "Chest" },
  { name: "Smith Machine Leg Press", bodyPart: "Quadriceps" },
  { name: "Smith Machine One-Arm Upright Row", bodyPart: "Shoulders" },
  { name: "Smith Machine Overhead Shoulder Press", bodyPart: "Shoulders" },
  { name: "Smith Machine Pistol Squat", bodyPart: "Quadriceps" },
  { name: "Smith Machine Reverse Calf Raises", bodyPart: "Calves" },
  { name: "Smith Machine Shrug", bodyPart: "Traps" },
  { name: "Smith Machine Squat", bodyPart: "Quadriceps" },
  { name: "Smith Machine Stiff-Legged Deadlift", bodyPart: "Hamstrings" },
  { name: "Smith Machine Upright Row", bodyPart: "Traps" },
  { name: "Smith Single-Leg Split Squat", bodyPart: "Quadriceps" },
  { name: "Snatch", bodyPart: "Quadriceps" },
  { name: "Snatch Balance", bodyPart: "Quadriceps" },
  { name: "Snatch Deadlift", bodyPart: "Hamstrings" },
  { name: "Snatch From Blocks", bodyPart: "Quadriceps" },
  { name: "Snatch Pull", bodyPart: "Hamstrings" },
  { name: "Snatch Shrug", bodyPart: "Traps" },
  { name: "Speed Band Overhead Triceps", bodyPart: "Triceps" },
  { name: "Speed Band Pushdown", bodyPart: "Triceps" },
  { name: "Speed Box Squat", bodyPart: "Quadriceps" },
  { name: "Speed Squats", bodyPart: "Quadriceps" },
  { name: "Spell Caster", bodyPart: "Abdominals" },
  { name: "Spider Crawl", bodyPart: "Abdominals" },
  { name: "Spider Curl", bodyPart: "Biceps" },
  { name: "Spinal Stretch", bodyPart: "Middle Back" },
  { name: "Split Clean", bodyPart: "Quadriceps" },
  { name: "Split Jerk", bodyPart: "Quadriceps" },
  { name: "Split Jump", bodyPart: "Quadriceps" },
  { name: "Split Snatch", bodyPart: "Hamstrings" },
  { name: "Split Squat With Dumbbells", bodyPart: "Quadriceps" },
  { name: "Split Squats", bodyPart: "Hamstrings" },
  { name: "Squat Jerk", bodyPart: "Quadriceps" },
  { name: "Squat With Bands", bodyPart: "Quadriceps" },
  { name: "Squat With Chains", bodyPart: "Quadriceps" },
  { name: "Squat With Plate Movers", bodyPart: "Quadriceps" },
  { name: "Squats - With Bands", bodyPart: "Quadriceps" },
  { name: "Stairmaster", bodyPart: "Quadriceps" },
  { name: "Standing Alternating Dumbbell Press", bodyPart: "Shoulders" },
  { name: "Standing Barbell Calf Raise", bodyPart: "Calves" },
  { name: "Standing Barbell Press Behind Neck", bodyPart: "Shoulders" },
  {
    name: "Standing Bent-Over One-Arm Dumbbell Triceps Extension",
    bodyPart: "Triceps",
  },
  {
    name: "Standing Bent-Over Two-Arm Dumbbell Triceps Extension",
    bodyPart: "Triceps",
  },
  { name: "Standing Biceps Cable Curl", bodyPart: "Biceps" },
  { name: "Standing Biceps Stretch", bodyPart: "Biceps" },
  { name: "Standing Bradford Press", bodyPart: "Shoulders" },
  { name: "Standing Cable Chest Press", bodyPart: "Chest" },
  { name: "Standing Cable Lift", bodyPart: "Abdominals" },
  { name: "Standing Cable Wood Chop", bodyPart: "Abdominals" },
  { name: "Standing Calf Raises", bodyPart: "Calves" },
  { name: "Standing Concentration Curl", bodyPart: "Biceps" },
  { name: "Standing Dumbbell Calf Raise", bodyPart: "Calves" },
  { name: "Standing Dumbbell Press", bodyPart: "Shoulders" },
  { name: "Standing Dumbbell Reverse Curl", bodyPart: "Biceps" },
  {
    name: "Standing Dumbbell Straight-Arm Front Delt Raise Above Head",
    bodyPart: "Shoulders",
  },
  { name: "Standing Dumbbell Triceps Extension", bodyPart: "Triceps" },
  { name: "Standing Dumbbell Upright Row", bodyPart: "Traps" },
  { name: "Standing Elevated Quad Stretch", bodyPart: "Quadriceps" },
  { name: "Standing Front Barbell Raise Over Head", bodyPart: "Shoulders" },
  { name: "Standing Gastrocnemius Calf Stretch", bodyPart: "Calves" },
  { name: "Standing Hamstring And Calf Stretch", bodyPart: "Hamstrings" },
  { name: "Standing Hip Circles", bodyPart: "Abductors" },
  { name: "Standing Hip Flexors", bodyPart: "Quadriceps" },
  { name: "Standing Inner-Biceps Curl", bodyPart: "Biceps" },
  { name: "Standing Lateral Stretch", bodyPart: "Abdominals" },
  { name: "Standing Leg Curl", bodyPart: "Hamstrings" },
  { name: "Standing Long Jump", bodyPart: "Quadriceps" },
  { name: "Standing Low-Pulley Deltoid Raise", bodyPart: "Shoulders" },
  {
    name: "Standing Low-Pulley One-Arm Triceps Extension",
    bodyPart: "Triceps",
  },
  { name: "Standing Military Press", bodyPart: "Shoulders" },
  { name: "Standing Olympic Plate Hand Squeeze", bodyPart: "Forearms" },
  { name: "Standing One-Arm Cable Curl", bodyPart: "Biceps" },
  {
    name: "Standing One-Arm Dumbbell Curl Over Incline Bench",
    bodyPart: "Biceps",
  },
  { name: "Standing One-Arm Dumbbell Triceps Extension", bodyPart: "Triceps" },
  { name: "Standing Overhead Barbell Triceps Extension", bodyPart: "Triceps" },
  { name: "Standing Palm-In One-Arm Dumbbell Press", bodyPart: "Shoulders" },
  { name: "Standing Palms-In Dumbbell Press", bodyPart: "Shoulders" },
  {
    name: "Standing Palms-Up Barbell Behind The Back Wrist Curl",
    bodyPart: "Forearms",
  },
  { name: "Standing Pelvic Tilt", bodyPart: "Lower Back" },
  { name: "Standing Rope Crunch", bodyPart: "Abdominals" },
  { name: "Standing Soleus And Achilles Stretch", bodyPart: "Calves" },
  { name: "Standing Toe Touches", bodyPart: "Hamstrings" },
  { name: "Standing Towel Triceps Extension", bodyPart: "Triceps" },
  { name: "Standing Two-Arm Overhead Throw", bodyPart: "Shoulders" },
  { name: "Star Jump", bodyPart: "Quadriceps" },
  { name: "Step Mill", bodyPart: "Quadriceps" },
  { name: "Step-Up With Knee Raise", bodyPart: "Glutes" },
  { name: "Stiff Leg Barbell Good Morning", bodyPart: "Lower Back" },
  { name: "Stiff-Legged Barbell Deadlift", bodyPart: "Hamstrings" },
  { name: "Stiff-Legged Dumbbell Deadlift", bodyPart: "Hamstrings" },
  { name: "Stomach Vacuum", bodyPart: "Abdominals" },
  { name: "Straight Bar Bench Mid Rows", bodyPart: "Middle Back" },
  { name: "Straight Raises On Incline Bench", bodyPart: "Shoulders" },
  { name: "Straight-Arm Dumbbell Pullover", bodyPart: "Chest" },
  { name: "Straight-Arm Pulldown", bodyPart: "Lats" },
  { name: "Stride Jump Crossover", bodyPart: "Quadriceps" },
  { name: "Sumo Deadlift With Bands", bodyPart: "Hamstrings" },
  { name: "Sumo Deadlift With Chains", bodyPart: "Hamstrings" },
  { name: "Superman", bodyPart: "Lower Back" },
  { name: "Supine Chest Throw", bodyPart: "Triceps" },
  { name: "Supine One-Arm Overhead Throw", bodyPart: "Abdominals" },
  { name: "Supine Two-Arm Overhead Throw", bodyPart: "Abdominals" },
  { name: "Suspended Push-Up", bodyPart: "Chest" },
  { name: "Suspended Reverse Crunch", bodyPart: "Abdominals" },
  { name: "Suspended Row", bodyPart: "Middle Back" },
  { name: "Suspended Split Squat", bodyPart: "Quadriceps" },
  { name: "T-Bar Row With Handle", bodyPart: "Middle Back" },
  { name: "Tate Press", bodyPart: "Triceps" },
  { name: "The Straddle", bodyPart: "Hamstrings" },
  { name: "Thigh Abductor", bodyPart: "Abductors" },
  { name: "Thigh Adductor", bodyPart: "Adductors" },
  { name: "Tire Flip", bodyPart: "Quadriceps" },
  { name: "Toe Touchers", bodyPart: "Abdominals" },
  { name: "Torso Rotation", bodyPart: "Abdominals" },
  { name: "Trail Running/Walking", bodyPart: "Quadriceps" },
  { name: "Trap Bar Deadlift", bodyPart: "Quadriceps" },
  { name: "Tricep Dumbbell Kickback", bodyPart: "Triceps" },
  { name: "Tricep Side Stretch", bodyPart: "Triceps" },
  { name: "Triceps Overhead Extension With Rope", bodyPart: "Triceps" },
  { name: "Triceps Pushdown", bodyPart: "Triceps" },
  { name: "Triceps Pushdown - Rope Attachment", bodyPart: "Triceps" },
  { name: "Triceps Pushdown - V-Bar Attachment", bodyPart: "Triceps" },
  { name: "Triceps Stretch", bodyPart: "Triceps" },
  { name: "Tuck Crunch", bodyPart: "Abdominals" },
  { name: "Two-Arm Dumbbell Preacher Curl", bodyPart: "Biceps" },
  { name: "Two-Arm Kettlebell Clean", bodyPart: "Shoulders" },
  { name: "Two-Arm Kettlebell Jerk", bodyPart: "Shoulders" },
  { name: "Two-Arm Kettlebell Military Press", bodyPart: "Shoulders" },
  { name: "Two-Arm Kettlebell Row", bodyPart: "Middle Back" },
  { name: "Underhand Cable Pulldowns", bodyPart: "Lats" },
  { name: "Upper Back Stretch", bodyPart: "Middle Back" },
  { name: "Upper Back-Leg Grab", bodyPart: "Hamstrings" },
  { name: "Upright Barbell Row", bodyPart: "Shoulders" },
  { name: "Upright Cable Row", bodyPart: "Traps" },
  { name: "Upright Row - With Bands", bodyPart: "Traps" },
  { name: "V-Bar Pulldown", bodyPart: "Lats" },
  { name: "V-Bar Pullup", bodyPart: "Lats" },
  { name: "Vertical Swing", bodyPart: "Hamstrings" },
  { name: "Walking", bodyPart: "Treadmill" },
  { name: "Weighted Ball Hyperextension", bodyPart: "Lower Back" },
  { name: "Weighted Ball Side Bend", bodyPart: "Abdominals" },
  { name: "Weighted Bench Dip", bodyPart: "Triceps" },
  { name: "Weighted Crunches", bodyPart: "Abdominals" },
  { name: "Weighted Jump Squat", bodyPart: "Quadriceps" },
  { name: "Weighted Pull Ups", bodyPart: "Lats" },
  { name: "Weighted Sissy Squat", bodyPart: "Quadriceps" },
  { name: "Weighted Sit-Ups - With Bands", bodyPart: "Abdominals" },
  { name: "Weighted Squat", bodyPart: "Quadriceps" },
  { name: "Wide Stance Barbell Squat", bodyPart: "Quadriceps" },
  { name: "Wide Stance Stiff Legs", bodyPart: "Hamstrings" },
  { name: "Wide-Grip Barbell Bench Press", bodyPart: "Chest" },
];

export default exerciseData;
