/** Sourced from https://github.com/davejt/exercise/edit/master/data/exercises */
const exerciseData = [
    { name: 'Ab Crunch Machine', bodyPart: 'Abdominals' },
    { name: 'Ab Roller', bodyPart: 'Abdominals' },
    { name: 'Adductor', bodyPart: 'Adductors' },
    { name: 'Air Bike', bodyPart: 'Abdominals' },
    { name: 'Alternate Hammer Curl', bodyPart: 'Biceps' },
    { name: 'Alternate Heel Touchers', bodyPart: 'Abdominals' },
    { name: 'Alternate Incline Dumbbell Curl', bodyPart: 'Biceps' },
    { name: 'Alternate Leg Diagonal Bound', bodyPart: 'Quadriceps' },
    { name: 'Alternating Cable Shoulder Press', bodyPart: 'Shoulders' },
    { name: 'Alternating Deltoid Raise', bodyPart: 'Shoulders' },
    { name: 'Alternating Floor Press', bodyPart: 'Chest' },
    { name: 'Alternating Hang Clean', bodyPart: 'Hamstrings' },
    { name: 'Alternating Kettlebell Press', bodyPart: 'Shoulders' },
    { name: 'Alternating Kettlebell Row', bodyPart: 'Middle Back' },
    { name: 'Alternating Renegade Row', bodyPart: 'Middle Back' },
    { name: 'Ankle Circles', bodyPart: 'Calves' },
    { name: 'Anti-Gravity Press', bodyPart: 'Shoulders' },
    { name: 'Arm Circles', bodyPart: 'Shoulders' },
    { name: 'Arnold Dumbbell Press', bodyPart: 'Shoulders' },
    { name: 'Around The Worlds', bodyPart: 'Chest' },
    { name: 'Atlas Stone Trainer', bodyPart: 'Lower Back' },
    { name: 'Atlas Stones', bodyPart: 'Lower Back' },
    { name: 'Axle Deadlift', bodyPart: 'Lower Back' },
    { name: 'Advanced Kettlebell Windmill', bodyPart: 'Abdominals' },
    { name: 'Back Flyes - With Bands', bodyPart: 'Shoulders' },
    { name: 'Backward Medicine Ball Throw', bodyPart: 'Shoulders' },
    { name: 'Balance Board', bodyPart: 'Calves' },
    { name: 'Ball Leg Curl', bodyPart: 'Hamstrings' },
    { name: 'Band Assisted Pull-Up', bodyPart: 'Lats' },
    { name: 'Band Good Morning', bodyPart: 'Hamstrings' },
    { name: 'Band Hip Adductions', bodyPart: 'Adductors' },
    { name: 'Band Pull Apart', bodyPart: 'Shoulders' },
    { name: 'Band Skull Crusher', bodyPart: 'Triceps' },
    { name: 'Barbell Ab Rollout', bodyPart: 'Abdominals' },
    { name: 'Barbell Ab Rollout - On Knees', bodyPart: 'Abdominals' },
    { name: 'Barbell Bench Press - Medium Grip', bodyPart: 'Chest' },
    { name: 'Barbell Curl', bodyPart: 'Biceps' },
    { name: 'Barbell Curls Lying Against An Incline', bodyPart: 'Biceps' },
    { name: 'Barbell Deadlift', bodyPart: 'Lower Back' },
    { name: 'Barbell Full Squat', bodyPart: 'Quadriceps' },
    { name: 'Barbell Glute Bridge', bodyPart: 'Glutes' },
    { name: 'Barbell Guillotine Bench Press', bodyPart: 'Chest' },
    { name: 'Barbell Hack Squat', bodyPart: 'Quadriceps' },
    { name: 'Barbell Hip Thrust', bodyPart: 'Glutes' },
    { name: 'Barbell Incline Bench Press - Medium Grip', bodyPart: 'Chest' },
    { name: 'Barbell Incline Shoulder Raise', bodyPart: 'Shoulders' },
    { name: 'Barbell Lunge', bodyPart: 'Quadriceps' },
    { name: 'Barbell Rear Delt Row', bodyPart: 'Shoulders' },
    { name: 'Barbell Rollout From Bench', bodyPart: 'Abdominals' },
    { name: 'Barbell Seated Calf Raise', bodyPart: 'Calves' },
    { name: 'Barbell Shoulder Press', bodyPart: 'Shoulders' },
    { name: 'Barbell Shrug', bodyPart: 'Traps' },
    { name: 'Barbell Shrug Behind The Back', bodyPart: 'Traps' },
    { name: 'Barbell Side Bend', bodyPart: 'Abdominals' },
    { name: 'Barbell Side Split Squat', bodyPart: 'Quadriceps' },
    { name: 'Barbell Squat', bodyPart: 'Quadriceps' },
    { name: 'Barbell Squat To A Bench', bodyPart: 'Quadriceps' },
    { name: 'Barbell Step Ups', bodyPart: 'Quadriceps' },
    { name: 'Barbell Walking Lunge', bodyPart: 'Quadriceps' },
    { name: 'Battling Ropes', bodyPart: 'Shoulders' },
    { name: 'Bear Crawl Sled Drags', bodyPart: 'Quadriceps' },
    { name: 'Behind Head Chest Stretch', bodyPart: 'Chest' },
    { name: 'Bench Dips', bodyPart: 'Triceps' },
    { name: 'Bench Jump', bodyPart: 'Quadriceps' },
    { name: 'Bench Press - Powerlifting', bodyPart: 'Triceps' },
    { name: 'Bench Press - With Bands', bodyPart: 'Chest' },
    { name: 'Bench Press With Chains', bodyPart: 'Triceps' },
    { name: 'Bench Sprint', bodyPart: 'Quadriceps' },
    { name: 'Bent Over Barbell Row', bodyPart: 'Middle Back' },
    { name: 'Bent Over Dumbbell Rear Delt Raise With Head On Bench', bodyPart: 'Shoulders' },
    { name: 'Bent Over Low-Pulley Side Lateral', bodyPart: 'Shoulders' },
    { name: 'Bent Over One-Arm Long Bar Row', bodyPart: 'Middle Back' },
    { name: 'Bent Over Two-Arm Long Bar Row', bodyPart: 'Middle Back' },
    { name: 'Bent Over Two-Dumbbell Row', bodyPart: 'Middle Back' },
    { name: 'Bent Over Two-Dumbbell Row With Palms In', bodyPart: 'Middle Back' },
    { name: 'Bent Press', bodyPart: 'Abdominals' },
    { name: 'Bent-Arm Barbell Pullover', bodyPart: 'Lats' },
    { name: 'Bent-Arm Dumbbell Pullover', bodyPart: 'Chest' },
    { name: 'Bent-Knee Hip Raise', bodyPart: 'Abdominals' },
    { name: 'Bicycling', bodyPart: 'Quadriceps' },
    { name: 'Board Press', bodyPart: 'Triceps' },
    { name: 'Body Tricep Press', bodyPart: 'Triceps' },
    { name: 'Body-Up', bodyPart: 'Triceps' },
    { name: 'Bodyweight Flyes', bodyPart: 'Chest' },
    { name: 'Bodyweight Mid Row', bodyPart: 'Middle Back' },
    { name: 'Bodyweight Squat', bodyPart: 'Quadriceps' },
    { name: 'Bodyweight Walking Lunge', bodyPart: 'Quadriceps' },
    { name: 'Bosu Ball Cable Crunch With Side Bends', bodyPart: 'Abdominals' },
    { name: 'Bottoms Up', bodyPart: 'Abdominals' },
    { name: 'Bottoms-Up Clean From The Hang Position', bodyPart: 'Forearms' },
    { name: 'Box Jump (Multiple Response)', bodyPart: 'Hamstrings' },
    { name: 'Box Skip', bodyPart: 'Hamstrings' },
    { name: 'Box Squat', bodyPart: 'Quadriceps' },
    { name: 'Box Squat With Bands', bodyPart: 'Quadriceps' },
    { name: 'Box Squat With Chains', bodyPart: 'Quadriceps' },
    { name: 'Brachialis-Smr', bodyPart: 'Biceps' },
    { name: 'Bradford/Rocky Presses', bodyPart: 'Shoulders' },
    { name: 'Butt Lift (Bridge)', bodyPart: 'Glutes' },
    { name: 'Butt-Ups', bodyPart: 'Abdominals' },
    { name: 'Butterfly', bodyPart: 'Chest' },
    { name: 'Cable Chest Press', bodyPart: 'Chest' },
    { name: 'Cable Crossover', bodyPart: 'Chest' },
    { name: 'Cable Crunch', bodyPart: 'Abdominals' },
    { name: 'Cable Deadlifts', bodyPart: 'Quadriceps' },
    { name: 'Cable Hammer Curls - Rope Attachment', bodyPart: 'Biceps' },
    { name: 'Cable Hip Adduction', bodyPart: 'Quadriceps' },
    { name: 'Cable Incline Pushdown', bodyPart: 'Lats' },
    { name: 'Cable Incline Triceps Extension', bodyPart: 'Triceps' },
    { name: 'Cable Internal Rotation', bodyPart: 'Shoulders' },
    { name: 'Cable Iron Cross', bodyPart: 'Chest' },
    { name: 'Cable Judo Flip', bodyPart: 'Abdominals' },
    { name: 'Cable Lying Triceps Extension', bodyPart: 'Triceps' },
    { name: 'Cable One Arm Tricep Extension', bodyPart: 'Triceps' },
    { name: 'Cable Preacher Curl', bodyPart: 'Biceps' },
    { name: 'Cable Rear Delt Fly', bodyPart: 'Shoulders' },
    { name: 'Cable Reverse Crunch', bodyPart: 'Abdominals' },
    { name: 'Cable Rope Overhead Triceps Extension', bodyPart: 'Triceps' },
    { name: 'Cable Rope Rear-Delt Rows', bodyPart: 'Shoulders' },
    { name: 'Cable Russian Twists', bodyPart: 'Abdominals' },
    { name: 'Cable Seated Crunch', bodyPart: 'Abdominals' },
    { name: 'Cable Seated Lateral Raise', bodyPart: 'Shoulders' },
    { name: 'Cable Shoulder Press', bodyPart: 'Shoulders' },
    { name: 'Cable Shrugs', bodyPart: 'Traps' },
    { name: 'Cable Tuck Reverse Crunch', bodyPart: 'Abdominals' },
    { name: 'Cable Wrist Curl', bodyPart: 'Forearms' },
    { name: 'Calf Press', bodyPart: 'Calves' },
    { name: 'Calf Press On The Leg Press Machine', bodyPart: 'Calves' },
    { name: 'Calf Raise On A Dumbbell', bodyPart: 'Calves' },
    { name: 'Calf Raises - With Bands', bodyPart: 'Calves' },
    { name: 'Calf Stretch Elbows Against Wall', bodyPart: 'Calves' },
    { name: 'Calf Stretch Hands Against Wall', bodyPart: 'Calves' },
    { name: 'Calf-Machine Shoulder Shrug', bodyPart: 'Traps' },
    { name: 'Calves-Smr', bodyPart: 'Calves' },
    { name: 'Car Deadlift', bodyPart: 'Quadriceps' },
    { name: 'Car Drivers', bodyPart: 'Shoulders' },
    { name: 'Carioca Quick Step', bodyPart: 'Adductors' },
    { name: 'Cat Stretch', bodyPart: 'Lower Back' },
    { name: 'Catch And Overhead Throw', bodyPart: 'Lats' },
    { name: 'Chain Handle Extension', bodyPart: 'Triceps' },
    { name: 'Chain Press', bodyPart: 'Chest' },
    { name: 'Chair Leg Extended Stretch', bodyPart: 'Hamstrings' },
    { name: 'Chair Lower Back Stretch', bodyPart: 'Lats' },
    { name: 'Chair Squat', bodyPart: 'Quadriceps' },
    { name: 'Chair Upper Body Stretch', bodyPart: 'Shoulders' },
    { name: 'Chest And Front Of Shoulder Stretch', bodyPart: 'Chest' },
    { name: 'Chest Push (Multiple Response)', bodyPart: 'Chest' },
    { name: 'Chest Push (Single Response)', bodyPart: 'Chest' },
    { name: 'Chest Push From 3 Point Stance', bodyPart: 'Chest' },
    { name: 'Chest Push With Run Release', bodyPart: 'Chest' },
    { name: 'Chest Stretch On Stability Ball', bodyPart: 'Chest' },
    { name: 'Childs Pose', bodyPart: 'Lower Back' },
    { name: 'Chin To Chest Stretch', bodyPart: 'Neck' },
    { name: 'Chin-Up', bodyPart: 'Lats' },
    { name: 'Circus Bell', bodyPart: 'Shoulders' },
    { name: 'Clean', bodyPart: 'Hamstrings' },
    { name: 'Clean And Jerk', bodyPart: 'Shoulders' },
    { name: 'Clean And Press', bodyPart: 'Shoulders' },
    { name: 'Clean Deadlift', bodyPart: 'Hamstrings' },
    { name: 'Clean From Blocks', bodyPart: 'Quadriceps' },
    { name: 'Clean Pull', bodyPart: 'Quadriceps' },
    { name: 'Clean Shrug', bodyPart: 'Traps' },
    { name: 'Clock Push-Up', bodyPart: 'Chest' },
    { name: 'Close-Grip Barbell Bench Press', bodyPart: 'Triceps' },
    { name: 'Close-Grip Dumbbell Press', bodyPart: 'Triceps' },
    { name: 'Close-Grip Ez Bar Curl', bodyPart: 'Biceps' },
    { name: 'Close-Grip Ez-Bar Curl With Band', bodyPart: 'Biceps' },
    { name: 'Close-Grip Ez-Bar Press', bodyPart: 'Triceps' },
    { name: 'Close-Grip Front Lat Pulldown', bodyPart: 'Lats' },
    { name: 'Close-Grip Push-Up Off Of A Dumbbell', bodyPart: 'Triceps' },
    { name: 'Close-Grip Standing Barbell Curl', bodyPart: 'Biceps' },
    { name: 'Cocoons', bodyPart: 'Abdominals' },
    { name: 'Conans Wheel', bodyPart: 'Quadriceps' },
    { name: 'Concentration Curls', bodyPart: 'Biceps' },
    { name: 'Cross Body Hammer Curl', bodyPart: 'Biceps' },
    { name: 'Cross Over - With Bands', bodyPart: 'Chest' },
    { name: 'Cross-Body Crunch', bodyPart: 'Abdominals' },
    { name: 'Crossover Reverse Lunge', bodyPart: 'Lower Back' },
    { name: 'Crucifix', bodyPart: 'Shoulders' },
    { name: 'Crunch - Hands Overhead', bodyPart: 'Abdominals' },
    { name: 'Crunch - Legs On Exercise Ball', bodyPart: 'Abdominals' },
    { name: 'Crunches', bodyPart: 'Abdominals' },
    { name: 'Cuban Press', bodyPart: 'Shoulders' },
    { name: 'Dancers Stretch', bodyPart: 'Lower Back' },
    { name: 'Deadlift With Bands', bodyPart: 'Lower Back' },
    { name: 'Deadlift With Chains', bodyPart: 'Lower Back' },
    { name: 'Decline Barbell Bench Press', bodyPart: 'Chest' },
    { name: 'Decline Close-Grip Bench To Skull Crusher', bodyPart: 'Triceps' },
    { name: 'Decline Crunch', bodyPart: 'Abdominals' },
    { name: 'Decline Dumbbell Bench Press', bodyPart: 'Chest' },
    { name: 'Decline Dumbbell Flyes', bodyPart: 'Chest' },
    { name: 'Decline Dumbbell Triceps Extension', bodyPart: 'Triceps' },
    { name: 'Decline Ez Bar Triceps Extension', bodyPart: 'Triceps' },
    { name: 'Decline Oblique Crunch', bodyPart: 'Abdominals' },
    { name: 'Decline Push-Up', bodyPart: 'Chest' },
    { name: 'Decline Reverse Crunch', bodyPart: 'Abdominals' },
    { name: 'Decline Smith Press', bodyPart: 'Chest' },
    { name: 'Deficit Deadlift', bodyPart: 'Lower Back' },
    { name: 'Depth Jump Leap', bodyPart: 'Quadriceps' },
    { name: 'Dip Machine', bodyPart: 'Triceps' },
    { name: 'Dips - Chest Version', bodyPart: 'Chest' },
    { name: 'Dips - Triceps Version', bodyPart: 'Triceps' },
    { name: 'Donkey Calf Raises', bodyPart: 'Calves' },
    { name: 'Double Kettlebell Alternating Hang Clean', bodyPart: 'Hamstrings' },
    { name: 'Double Kettlebell Jerk', bodyPart: 'Shoulders' },
    { name: 'Double Kettlebell Push Press', bodyPart: 'Shoulders' },
    { name: 'Double Kettlebell Snatch', bodyPart: 'Shoulders' },
    { name: 'Double Kettlebell Windmill', bodyPart: 'Abdominals' },
    { name: 'Double Leg Butt Kick', bodyPart: 'Quadriceps' },
    { name: 'Downward Facing Balance', bodyPart: 'Glutes' },
    { name: 'Drag Curl', bodyPart: 'Biceps' },
    { name: 'Drop Push', bodyPart: 'Chest' },
    { name: 'Dumbbell Alternate Bicep Curl', bodyPart: 'Biceps' },
    { name: 'Dumbbell Bench Press', bodyPart: 'Chest' },
    { name: 'Dumbbell Bench Press With Neutral Grip', bodyPart: 'Chest' },
    { name: 'Dumbbell Bicep Curl', bodyPart: 'Biceps' },
    { name: 'Dumbbell Clean', bodyPart: 'Hamstrings' },
    { name: 'Dumbbell Floor Press', bodyPart: 'Triceps' },
    { name: 'Dumbbell Flyes', bodyPart: 'Chest' },
    { name: 'Dumbbell Incline Row', bodyPart: 'Middle Back' },
    { name: 'Dumbbell Incline Shoulder Raise', bodyPart: 'Shoulders' },
    { name: 'Dumbbell Lunges', bodyPart: 'Quadriceps' },
    { name: 'Dumbbell Lying One-Arm Rear Lateral Raise', bodyPart: 'Shoulders' },
    { name: 'Dumbbell Lying Pronation', bodyPart: 'Forearms' },
    { name: 'Dumbbell Lying Rear Lateral Raise', bodyPart: 'Shoulders' },
    { name: 'Dumbbell Lying Supination', bodyPart: 'Forearms' },
    { name: 'Dumbbell One-Arm Shoulder Press', bodyPart: 'Shoulders' },
    { name: 'Dumbbell One-Arm Triceps Extension', bodyPart: 'Triceps' },
    { name: 'Dumbbell One-Arm Upright Row', bodyPart: 'Shoulders' },
    { name: 'Dumbbell Prone Incline Curl', bodyPart: 'Biceps' },
    { name: 'Dumbbell Raise', bodyPart: 'Shoulders' },
    { name: 'Dumbbell Rear Lunge', bodyPart: 'Quadriceps' },
    { name: 'Dumbbell Scaption', bodyPart: 'Shoulders' },
    { name: 'Dumbbell Seated Box Jump', bodyPart: 'Quadriceps' },
    { name: 'Dumbbell Seated One-Leg Calf Raise', bodyPart: 'Calves' },
    { name: 'Dumbbell Shoulder Press', bodyPart: 'Shoulders' },
    { name: 'Dumbbell Shrug', bodyPart: 'Traps' },
    { name: 'Dumbbell Side Bend', bodyPart: 'Abdominals' },
    { name: 'Dumbbell Squat', bodyPart: 'Quadriceps' },
    { name: 'Dumbbell Squat To A Bench', bodyPart: 'Quadriceps' },
    { name: 'Dumbbell Step Ups', bodyPart: 'Quadriceps' },
    { name: 'Dumbbell Tricep Extension -Pronated Grip', bodyPart: 'Triceps' },
    { name: 'Dynamic Back Stretch', bodyPart: 'Lats' },
    { name: 'Dynamic Chest Stretch', bodyPart: 'Chest' },
    { name: 'Elbow Circles', bodyPart: 'Shoulders' },
    { name: 'Elbow To Knee', bodyPart: 'Abdominals' },
    { name: 'Elbows Back', bodyPart: 'Chest' },
    { name: 'Elevated Back Lunge', bodyPart: 'Quadriceps' },
    { name: 'Elevated Cable Rows', bodyPart: 'Lats' },
    { name: 'Elliptical Trainer', bodyPart: 'Quadriceps' },
    { name: 'Exercise Ball Crunch', bodyPart: 'Abdominals' },
    { name: 'Exercise Ball Pull-In', bodyPart: 'Abdominals' },
    { name: 'Extended Range One-Arm Kettlebell Floor Press', bodyPart: 'Chest' },
    { name: 'External Rotation', bodyPart: 'Shoulders' },
    { name: 'External Rotation With Band', bodyPart: 'Shoulders' },
    { name: 'External Rotation With Cable', bodyPart: 'Shoulders' },
    { name: 'Ez-Bar Curl', bodyPart: 'Biceps' },
    { name: 'Ez-Bar Skullcrusher', bodyPart: 'Triceps' },
    { name: 'Face Pull', bodyPart: 'Shoulders' },
    { name: 'Farmers Walk', bodyPart: 'Forearms' },
    { name: 'Fast Skipping', bodyPart: 'Quadriceps' },
    { name: 'Finger Curls', bodyPart: 'Forearms' },
    { name: 'Flat Bench Cable Flyes', bodyPart: 'Chest' },
    { name: 'Flat Bench Leg Pull-In', bodyPart: 'Abdominals' },
    { name: 'Flat Bench Lying Leg Raise', bodyPart: 'Abdominals' },
    { name: 'Flexor Incline Dumbbell Curls', bodyPart: 'Biceps' },
    { name: 'Floor Glute-Ham Raise', bodyPart: 'Hamstrings' },
    { name: 'Floor Press', bodyPart: 'Triceps' },
    { name: 'Floor Press With Chains', bodyPart: 'Triceps' },
    { name: 'Flutter Kicks', bodyPart: 'Glutes' },
    { name: 'Foot-Smr', bodyPart: 'Calves' },
    { name: 'Forward Drag With Press', bodyPart: 'Chest' },
    { name: 'Frankenstein Squat', bodyPart: 'Quadriceps' },
    { name: 'Freehand Jump Squat', bodyPart: 'Quadriceps' },
    { name: 'Frog Hops', bodyPart: 'Quadriceps' },
    { name: 'Frog Sit-Ups', bodyPart: 'Abdominals' },
    { name: 'Front Barbell Squat', bodyPart: 'Quadriceps' },
    { name: 'Front Barbell Squat To A Bench', bodyPart: 'Quadriceps' },
    { name: 'Front Box Jump', bodyPart: 'Hamstrings' },
    { name: 'Front Cable Raise', bodyPart: 'Shoulders' },
    { name: 'Front Cone Hops (Or Hurdle Hops)', bodyPart: 'Quadriceps' },
    { name: 'Front Dumbbell Raise', bodyPart: 'Shoulders' },
    { name: 'Front Incline Dumbbell Raise', bodyPart: 'Shoulders' },
    { name: 'Front Leg Raises', bodyPart: 'Hamstrings' },
    { name: 'Front Plate Raise', bodyPart: 'Shoulders' },
    { name: 'Front Raise And Pullover', bodyPart: 'Chest' },
    { name: 'Front Squat (Clean Grip)', bodyPart: 'Quadriceps' },
    { name: 'Front Squats With Two Kettlebells', bodyPart: 'Quadriceps' },
    { name: 'Front Two-Dumbbell Raise', bodyPart: 'Shoulders' },
    { name: 'Full Range-Of-Motion Lat Pulldown', bodyPart: 'Lats' },
    { name: 'Gironda Sternum Chins', bodyPart: 'Lats' },
    { name: 'Glute Ham Raise', bodyPart: 'Hamstrings' },
    { name: 'Glute Kickback', bodyPart: 'Glutes' },
    { name: 'Goblet Squat', bodyPart: 'Quadriceps' },
    { name: 'Good Morning', bodyPart: 'Hamstrings' },
    { name: 'Good Morning Off Pins', bodyPart: 'Hamstrings' },
    { name: 'Gorilla Chin/Crunch', bodyPart: 'Abdominals' },
    { name: 'Groin And Back Stretch', bodyPart: 'Adductors' },
    { name: 'Groiners', bodyPart: 'Adductors' },
    { name: 'Hack Squat', bodyPart: 'Quadriceps' },
    { name: 'Hammer Curls', bodyPart: 'Biceps' },
    { name: 'Hammer Grip Incline Db Bench Press', bodyPart: 'Chest' },
    { name: 'Hamstring Stretch', bodyPart: 'Hamstrings' },
    { name: 'Hamstring-Smr', bodyPart: 'Hamstrings' },
    { name: 'Handstand Push-Ups', bodyPart: 'Shoulders' },
    { name: 'Hang Clean', bodyPart: 'Quadriceps' },
    { name: 'Hang Clean - Below The Knees', bodyPart: 'Quadriceps' },
    { name: 'Hang Snatch', bodyPart: 'Hamstrings' },
    { name: 'Hang Snatch - Below Knees', bodyPart: 'Hamstrings' },
    { name: 'Hanging Bar Good Morning', bodyPart: 'Hamstrings' },
    { name: 'Hanging Leg Raise', bodyPart: 'Abdominals' },
    { name: 'Hanging Pike', bodyPart: 'Abdominals' },
    { name: 'Heaving Snatch Balance', bodyPart: 'Quadriceps' },
    { name: 'Heavy Bag Thrust', bodyPart: 'Chest' },
    { name: 'High Cable Curls', bodyPart: 'Biceps' },
    { name: 'Hip Circles (Prone)', bodyPart: 'Abductors' },
    { name: 'Hip Crossover', bodyPart: '' },
    { name: 'Hip Extension With Bands', bodyPart: 'Glutes' },
    { name: 'Hip Flexion With Band', bodyPart: 'Quadriceps' },
    { name: 'Hip Lift With Band', bodyPart: 'Glutes' },
    { name: 'Hug A Ball', bodyPart: 'Lower Back' },
    { name: 'Hug Knees To Chest', bodyPart: 'Lower Back' },
    { name: 'Hurdle Hops', bodyPart: 'Hamstrings' },
    { name: 'Hyperextensions (Back Extensions)', bodyPart: 'Lower Back' },
    { name: 'Hyperextensions With No Hyperextension Bench', bodyPart: 'Lower Back' },
    { name: 'Iliotibial Tract-Smr', bodyPart: 'Abductors' },
    { name: 'Incline Barbell Triceps Extension', bodyPart: 'Triceps' },
    { name: 'Incline Bench Pull', bodyPart: 'Middle Back' },
    { name: 'Incline Cable Chest Press', bodyPart: 'Chest' },
    { name: 'Incline Cable Flye', bodyPart: 'Chest' },
    { name: 'Incline Dumbbell Bench With Palms Facing In', bodyPart: 'Chest' },
    { name: 'Incline Dumbbell Curl', bodyPart: 'Biceps' },
    { name: 'Incline Dumbbell Flyes', bodyPart: 'Chest' },
    { name: 'Incline Dumbbell Flyes - With A Twist', bodyPart: 'Chest' },
    { name: 'Incline Dumbbell Press', bodyPart: 'Chest' },
    { name: 'Incline Hammer Curls', bodyPart: 'Biceps' },
    { name: 'Incline Inner Biceps Curl', bodyPart: 'Biceps' },
    { name: 'Incline Push-Up', bodyPart: 'Chest' },
    { name: 'Incline Push-Up Close-Grip', bodyPart: 'Triceps' },
    { name: 'Incline Push-Up Depth Jump', bodyPart: 'Chest' },
    { name: 'Incline Push-Up Medium', bodyPart: 'Chest' },
    { name: 'Incline Push-Up Reverse Grip', bodyPart: 'Chest' },
    { name: 'Incline Push-Up Wide', bodyPart: 'Chest' },
    { name: 'Intermediate Groin Stretch', bodyPart: 'Hamstrings' },
    { name: 'Intermediate Hip Flexor And Quad Stretch', bodyPart: 'Quadriceps' },
    { name: 'Internal Rotation With Band', bodyPart: 'Shoulders' },
    { name: 'Inverted Row', bodyPart: 'Middle Back' },
    { name: 'Inverted Row With Straps', bodyPart: 'Middle Back' },
    { name: 'Iron Cross', bodyPart: 'Shoulders' },
    { name: 'Iron Crosses (Stretch)', bodyPart: 'Quadriceps' },
    { name: 'Isometric Chest Squeezes', bodyPart: 'Chest' },
    { name: 'Isometric Neck Exercise - Front And Back', bodyPart: 'Neck' },
    { name: 'Isometric Neck Exercise - Sides', bodyPart: 'Neck' },
    { name: 'Isometric Wipers', bodyPart: 'Chest' },
    { name: 'It Band And Glute Stretch', bodyPart: 'Abductors' },
    { name: 'Jackknife Sit-Up', bodyPart: 'Abdominals' },
    { name: 'Janda Sit-Up', bodyPart: 'Abdominals' },
    { name: 'Jefferson Squats', bodyPart: 'Quadriceps' },
    { name: 'Jerk Balance', bodyPart: 'Shoulders' },
    { name: 'Jerk Dip Squat', bodyPart: 'Quadriceps' },
    { name: 'Jm Press', bodyPart: 'Triceps' },
    { name: 'Jogging-Treadmill', bodyPart: 'Quadriceps' },
    { name: 'Keg Load', bodyPart: 'Lower Back' },
    { name: 'Kettlebell Arnold Press', bodyPart: 'Shoulders' },
    { name: 'Kettlebell Dead Clean', bodyPart: 'Hamstrings' },
    { name: 'Kettlebell Figure 8', bodyPart: 'Abdominals' },
    { name: 'Kettlebell Hang Clean', bodyPart: 'Hamstrings' },
    { name: 'Kettlebell One-Legged Deadlift', bodyPart: 'Hamstrings' },
    { name: 'Kettlebell Pass Between The Legs', bodyPart: 'Abdominals' },
    { name: 'Kettlebell Pirate Ships', bodyPart: 'Shoulders' },
    { name: 'Kettlebell Pistol Squat', bodyPart: 'Quadriceps' },
    { name: 'Kettlebell Seated Press', bodyPart: 'Shoulders' },
    { name: 'Kettlebell Seesaw Press', bodyPart: 'Shoulders' },
    { name: 'Kettlebell Sumo High Pull', bodyPart: 'Traps' },
    { name: 'Kettlebell Thruster', bodyPart: 'Shoulders' },
    { name: 'Kettlebell Turkish Get-Up (Lunge Style)', bodyPart: 'Shoulders' },
    { name: 'Kettlebell Turkish Get-Up (Squat Style)', bodyPart: 'Shoulders' },
    { name: 'Kettlebell Windmill', bodyPart: 'Abdominals' },
    { name: 'Kipping Muscle Up', bodyPart: 'Lats' },
    { name: 'Knee Across The Body', bodyPart: 'Glutes' },
    { name: 'Knee Circles', bodyPart: 'Calves' },
    { name: 'Knee Tuck Jump', bodyPart: 'Hamstrings' },
    { name: 'Knee/Hip Raise On Parallel Bars', bodyPart: 'Abdominals' },
    { name: 'Kneeling Arm Drill', bodyPart: 'Shoulders' },
    { name: 'Kneeling Cable Crunch With Alternating Oblique Twists', bodyPart: 'Abdominals' },
    { name: 'Kneeling Cable Triceps Extension', bodyPart: 'Triceps' },
    { name: 'Kneeling Forearm Stretch', bodyPart: 'Forearms' },
    { name: 'Kneeling High Pulley Row', bodyPart: 'Lats' },
    { name: 'Kneeling Hip Flexor', bodyPart: 'Quadriceps' },
    { name: 'Kneeling Jump Squat', bodyPart: 'Glutes' },
    { name: 'Kneeling Single-Arm High Pulley Row', bodyPart: 'Lats' },
    { name: 'Kneeling Squat', bodyPart: 'Glutes' },
    { name: 'Landmine 180s', bodyPart: 'Abdominals' },
    { name: 'Landmine Linear Jammer', bodyPart: 'Shoulders' },
    { name: 'Lateral Bound', bodyPart: 'Adductors' },
    { name: 'Lateral Box Jump', bodyPart: 'Adductors' },
    { name: 'Lateral Cone Hops', bodyPart: 'Adductors' },
    { name: 'Lateral Raise - With Bands', bodyPart: 'Shoulders' },
    { name: 'Latissimus Dorsi-Smr', bodyPart: 'Lats' },
    { name: 'Leg Extensions', bodyPart: 'Quadriceps' },
    { name: 'Leg Lift', bodyPart: 'Glutes' },
    { name: 'Leg Press', bodyPart: 'Quadriceps' },
    { name: 'Leg Pull-In', bodyPart: 'Abdominals' },
    { name: 'Leg-Over Floor Press', bodyPart: 'Chest' },
    { name: 'Leg-Up Hamstring Stretch', bodyPart: 'Hamstrings' },
    { name: 'Leverage Chest Press', bodyPart: 'Chest' },
    { name: 'Leverage Deadlift', bodyPart: 'Quadriceps' },
    { name: 'Leverage Decline Chest Press', bodyPart: 'Chest' },
    { name: 'Leverage High Row', bodyPart: 'Middle Back' },
    { name: 'Leverage Incline Chest Press', bodyPart: 'Chest' },
    { name: 'Leverage Iso Row', bodyPart: 'Lats' },
    { name: 'Leverage Shoulder Press', bodyPart: 'Shoulders' },
    { name: 'Leverage Shrug', bodyPart: 'Traps' },
    { name: 'Linear 3-Part Start Technique', bodyPart: 'Hamstrings' },
    { name: 'Linear Acceleration Wall Drill', bodyPart: 'Hamstrings' },
    { name: 'Linear Depth Jump', bodyPart: 'Quadriceps' },
    { name: 'Log Lift', bodyPart: 'Shoulders' },
    { name: 'London Bridges', bodyPart: 'Lats' },
    { name: 'Looking At Ceiling', bodyPart: 'Quadriceps' },
    { name: 'Low Cable Crossover', bodyPart: 'Chest' },
    { name: 'Low Cable Triceps Extension', bodyPart: 'Triceps' },
    { name: 'Low Pulley Row To Neck', bodyPart: 'Shoulders' },
    { name: 'Lower Back Curl', bodyPart: 'Abdominals' },
    { name: 'Lower Back-Smr', bodyPart: 'Lower Back' },
    { name: 'Lunge Pass Through', bodyPart: 'Hamstrings' },
    { name: 'Lunge Sprint', bodyPart: 'Quadriceps' },
    { name: 'Lying Bent Leg Groin', bodyPart: 'Adductors' },
    { name: 'Lying Cable Curl', bodyPart: 'Biceps' },
    { name: 'Lying Cambered Barbell Row', bodyPart: 'Middle Back' },
    { name: 'Lying Close-Grip Bar Curl On High Pulley', bodyPart: 'Biceps' },
    { name: 'Lying Close-Grip Barbell Triceps Extension Behind The Head', bodyPart: 'Triceps' },
    { name: 'Lying Close-Grip Barbell Triceps Press To Chin', bodyPart: 'Triceps' },
    { name: 'Lying Crossover', bodyPart: 'Abductors' },
    { name: 'Lying Dumbbell Tricep Extension', bodyPart: 'Triceps' },
    { name: 'Lying Face Down Plate Neck Resistance', bodyPart: 'Neck' },
    { name: 'Lying Face Up Plate Neck Resistance', bodyPart: 'Neck' },
    { name: 'Lying Glute', bodyPart: 'Glutes' },
    { name: 'Lying Hamstring', bodyPart: 'Hamstrings' },
    { name: 'Lying High Bench Barbell Curl', bodyPart: 'Biceps' },
    { name: 'Lying Leg Curls', bodyPart: 'Hamstrings' },
    { name: 'Lying Machine Squat', bodyPart: 'Quadriceps' },
    { name: 'Lying One-Arm Lateral Raise', bodyPart: 'Shoulders' },
    { name: 'Lying Prone Quadriceps', bodyPart: 'Quadriceps' },
    { name: 'Lying Rear Delt Raise', bodyPart: 'Shoulders' },
    { name: 'Lying Supine Dumbbell Curl', bodyPart: 'Biceps' },
    { name: 'Lying T-Bar Row', bodyPart: 'Middle Back' },
    { name: 'Lying Triceps Press', bodyPart: 'Triceps' },
    { name: 'Machine Bench Press', bodyPart: 'Chest' },
    { name: 'Machine Bicep Curl', bodyPart: 'Biceps' },
    { name: 'Machine Preacher Curls', bodyPart: 'Biceps' },
    { name: 'Machine Shoulder (Military) Press', bodyPart: 'Shoulders' },
    { name: 'Machine Triceps Extension', bodyPart: 'Triceps' },
    { name: 'Medicine Ball Chest Pass', bodyPart: 'Chest' },
    { name: 'Medicine Ball Full Twist', bodyPart: 'Abdominals' },
    { name: 'Medicine Ball Scoop Throw', bodyPart: 'Shoulders' },
    { name: 'Middle Back Shrug', bodyPart: 'Middle Back' },
    { name: 'Middle Back Stretch', bodyPart: 'Middle Back' },
    { name: 'Mixed Grip Chin', bodyPart: 'Middle Back' },
    { name: 'Monster Walk', bodyPart: 'Abductors' },
    { name: 'Mountain Climbers', bodyPart: 'Quadriceps' },
    { name: 'Moving Claw Series', bodyPart: 'Hamstrings' },
    { name: 'Muscle Snatch', bodyPart: 'Hamstrings' },
    { name: 'Muscle Up', bodyPart: 'Lats' },
    { name: 'Narrow Stance Hack Squats', bodyPart: 'Quadriceps' },
    { name: 'Narrow Stance Leg Press', bodyPart: 'Quadriceps' },
    { name: 'Narrow Stance Squats', bodyPart: 'Quadriceps' },
    { name: 'Natural Glute Ham Raise', bodyPart: 'Hamstrings' },
    { name: 'Neck Press', bodyPart: 'Chest' },
    { name: 'Neck-Smr', bodyPart: 'Neck' },
    { name: 'Oblique Crunches', bodyPart: 'Abdominals' },
    { name: 'Oblique Crunches - On The Floor', bodyPart: 'Abdominals' },
    { name: 'Olympic Squat', bodyPart: 'Quadriceps' },
    { name: 'On Your Side Quad Stretch', bodyPart: 'Quadriceps' },
    { name: 'On-Your-Back Quad Stretch', bodyPart: 'Quadriceps' },
    { name: 'One Arm Against Wall', bodyPart: 'Lats' },
    { name: 'One Arm Chin-Up', bodyPart: 'Middle Back' },
    { name: 'One Arm Dumbbell Bench Press', bodyPart: 'Chest' },
    { name: 'One Arm Dumbbell Preacher Curl', bodyPart: 'Biceps' },
    { name: 'One Arm Floor Press', bodyPart: 'Triceps' },
    { name: 'One Arm Lat Pulldown', bodyPart: 'Lats' },
    { name: 'One Arm Pronated Dumbbell Triceps Extension', bodyPart: 'Triceps' },
    { name: 'One Arm Supinated Dumbbell Triceps Extension', bodyPart: 'Triceps' },
    { name: 'One Half Locust', bodyPart: 'Quadriceps' },
    { name: 'One Handed Hang', bodyPart: 'Lats' },
    { name: 'One Knee To Chest', bodyPart: 'Glutes' },
    { name: 'One Leg Barbell Squat', bodyPart: 'Quadriceps' },
    { name: 'One-Arm Dumbbell Row', bodyPart: 'Middle Back' },
    { name: 'One-Arm Flat Bench Dumbbell Flye', bodyPart: 'Chest' },
    { name: 'One-Arm High-Pulley Cable Side Bends', bodyPart: 'Abdominals' },
    { name: 'One-Arm Incline Lateral Raise', bodyPart: 'Shoulders' },
    { name: 'One-Arm Kettlebell Clean', bodyPart: 'Hamstrings' },
    { name: 'One-Arm Kettlebell Clean And Jerk', bodyPart: 'Shoulders' },
    { name: 'One-Arm Kettlebell Floor Press', bodyPart: 'Chest' },
    { name: 'One-Arm Kettlebell Jerk', bodyPart: 'Shoulders' },
    { name: 'One-Arm Kettlebell Military Press To The Side', bodyPart: 'Shoulders' },
    { name: 'One-Arm Kettlebell Para Press', bodyPart: 'Shoulders' },
    { name: 'One-Arm Kettlebell Push Press', bodyPart: 'Shoulders' },
    { name: 'One-Arm Kettlebell Row', bodyPart: 'Middle Back' },
    { name: 'One-Arm Kettlebell Snatch', bodyPart: 'Shoulders' },
    { name: 'One-Arm Kettlebell Split Jerk', bodyPart: 'Shoulders' },
    { name: 'One-Arm Kettlebell Split Snatch', bodyPart: 'Shoulders' },
    { name: 'One-Arm Kettlebell Swings', bodyPart: 'Hamstrings' },
    { name: 'One-Arm Long Bar Row', bodyPart: 'Middle Back' },
    { name: 'One-Arm Medicine Ball Slam', bodyPart: 'Abdominals' },
    { name: 'One-Arm Open Palm Kettlebell Clean', bodyPart: 'Hamstrings' },
    { name: 'One-Arm Overhead Kettlebell Squats', bodyPart: 'Quadriceps' },
    { name: 'One-Arm Side Deadlift', bodyPart: 'Quadriceps' },
    { name: 'One-Arm Side Laterals', bodyPart: 'Shoulders' },
    { name: 'One-Legged Cable Kickback', bodyPart: 'Glutes' },
    { name: 'Open Palm Kettlebell Clean', bodyPart: 'Hamstrings' },
    { name: 'Otis-Up', bodyPart: 'Abdominals' },
    { name: 'Overhead Cable Curl', bodyPart: 'Biceps' },
    { name: 'Overhead Lat', bodyPart: 'Lats' },
    { name: 'Overhead Slam', bodyPart: 'Lats' },
    { name: 'Overhead Squat', bodyPart: 'Quadriceps' },
    { name: 'Overhead Stretch', bodyPart: 'Abdominals' },
    { name: 'Overhead Triceps', bodyPart: 'Triceps' },
    { name: 'Pallof Press With Rotation', bodyPart: 'Abdominals' },
    { name: 'Palms-Down Dumbbell Wrist Curl Over A Bench', bodyPart: 'Forearms' },
    { name: 'Palms-Down Wrist Curl Over A Bench', bodyPart: 'Forearms' },
    { name: 'Palms-Up Barbell Wrist Curl Over A Bench', bodyPart: 'Forearms' },
    { name: 'Palms-Up Dumbbell Wrist Curl Over A Bench', bodyPart: 'Forearms' },
    { name: 'Parallel Bar Dip', bodyPart: 'Triceps' },
    { name: 'Pelvic Tilt Into Bridge', bodyPart: 'Lower Back' },
    { name: 'Peroneals Stretch', bodyPart: 'Calves' },
    { name: 'Peroneals-Smr', bodyPart: 'Calves' },
    { name: 'Physioball Hip Bridge', bodyPart: 'Glutes' },
    { name: 'Pin Presses', bodyPart: 'Triceps' },
    { name: 'Piriformis-Smr', bodyPart: 'Glutes' },
    { name: 'Plank', bodyPart: 'Abdominals' },
    { name: 'Plank With Twist', bodyPart: '' },
    { name: 'Plate Pinch', bodyPart: 'Forearms' },
    { name: 'Plate Twist', bodyPart: 'Abdominals' },
    { name: 'Platform Hamstring Slides', bodyPart: 'Hamstrings' },
    { name: 'Plie Dumbbell Squat', bodyPart: 'Quadriceps' },
    { name: 'Plyo Kettlebell Pushups', bodyPart: 'Chest' },
    { name: 'Plyo Push-Up', bodyPart: 'Chest' },
    { name: 'Posterior Tibialis Stretch', bodyPart: 'Calves' },
    { name: 'Power Clean', bodyPart: 'Hamstrings' },
    { name: 'Power Clean From Blocks', bodyPart: 'Hamstrings' },
    { name: 'Power Jerk', bodyPart: 'Quadriceps' },
    { name: 'Power Partials', bodyPart: 'Shoulders' },
    { name: 'Power Snatch', bodyPart: 'Hamstrings' },
    { name: 'Power Snatch From Blocks', bodyPart: 'Quadriceps' },
    { name: 'Power Stairs', bodyPart: 'Hamstrings' },
    { name: 'Preacher Curl', bodyPart: 'Biceps' },
    { name: 'Preacher Hammer Dumbbell Curl', bodyPart: 'Biceps' },
    { name: 'Press Sit-Up', bodyPart: 'Abdominals' },
    { name: 'Prone Manual Hamstring', bodyPart: 'Hamstrings' },
    { name: 'Prowler Sprint', bodyPart: 'Hamstrings' },
    { name: 'Pull Through', bodyPart: 'Glutes' },
    { name: 'Pullups', bodyPart: 'Lats' },
    { name: 'Push Press', bodyPart: 'Shoulders' },
    { name: 'Push Press - Behind The Neck', bodyPart: 'Shoulders' },
    { name: 'Push Up To Side Plank', bodyPart: 'Chest' },
    { name: 'Push-Up Wide', bodyPart: 'Chest' },
    { name: 'Push-Ups - Close Triceps Position', bodyPart: 'Triceps' },
    { name: 'Push-Ups With Feet Elevated', bodyPart: 'Chest' },
    { name: 'Push-Ups With Feet On An Exercise Ball', bodyPart: 'Chest' },
    { name: 'Pushups', bodyPart: 'Chest' },
    { name: 'Pushups (Close And Wide Hand Positions)', bodyPart: 'Chest' },
    { name: 'Pyramid', bodyPart: 'Lower Back' },
    { name: 'Quad Stretch', bodyPart: 'Quadriceps' },
    { name: 'Quadriceps-Smr', bodyPart: 'Quadriceps' },
    { name: 'Quick Leap', bodyPart: 'Quadriceps' },
    { name: 'Rack Delivery', bodyPart: 'Shoulders' },
    { name: 'Rack Pull With Bands', bodyPart: 'Lower Back' },
    { name: 'Rack Pulls', bodyPart: 'Lower Back' },
    { name: 'Rear Leg Raises', bodyPart: 'Quadriceps' },
    { name: 'Recumbent Bike', bodyPart: 'Quadriceps' },
    { name: 'Return Push From Stance', bodyPart: 'Shoulders' },
    { name: 'Reverse Band Bench Press', bodyPart: 'Triceps' },
    { name: 'Reverse Band Box Squat', bodyPart: 'Quadriceps' },
    { name: 'Reverse Band Deadlift', bodyPart: 'Lower Back' },
    { name: 'Reverse Band Power Squat', bodyPart: 'Quadriceps' },
    { name: 'Reverse Band Sumo Deadlift', bodyPart: 'Hamstrings' },
    { name: 'Reverse Barbell Curl', bodyPart: 'Biceps' },
    { name: 'Reverse Barbell Preacher Curls', bodyPart: 'Biceps' },
    { name: 'Reverse Cable Curl', bodyPart: 'Biceps' },
    { name: 'Reverse Crunch', bodyPart: 'Abdominals' },
    { name: 'Reverse Flyes', bodyPart: 'Shoulders' },
    { name: 'Reverse Flyes With External Rotation', bodyPart: 'Shoulders' },
    { name: 'Reverse Grip Bent-Over Rows', bodyPart: 'Middle Back' },
    { name: 'Reverse Grip Triceps Pushdown', bodyPart: 'Triceps' },
    { name: 'Reverse Hyperextension', bodyPart: 'Hamstrings' },
    { name: 'Reverse Machine Flyes', bodyPart: 'Shoulders' },
    { name: 'Reverse Plate Curls', bodyPart: 'Biceps' },
    { name: 'Reverse Triceps Bench Press', bodyPart: 'Triceps' },
    { name: 'Rhomboids-Smr', bodyPart: 'Middle Back' },
    { name: 'Rickshaw Carry', bodyPart: 'Forearms' },
    { name: 'Rickshaw Deadlift', bodyPart: 'Quadriceps' },
    { name: 'Ring Dips', bodyPart: 'Triceps' },
    { name: 'Rocket Jump', bodyPart: 'Quadriceps' },
    { name: 'Rocking Standing Calf Raise', bodyPart: 'Calves' },
    { name: 'Rocky Pull-Ups/Pulldowns', bodyPart: 'Lats' },
    { name: 'Romanian Deadlift', bodyPart: 'Hamstrings' },
    { name: 'Romanian Deadlift From Deficit', bodyPart: 'Hamstrings' },
    { name: 'Rope Climb', bodyPart: 'Lats' },
    { name: 'Rope Crunch', bodyPart: 'Abdominals' },
    { name: 'Rope Jumping', bodyPart: 'Quadriceps' },
    { name: 'Rope Straight-Arm Pulldown', bodyPart: 'Lats' },
    { name: 'Round The World Shoulder Stretch', bodyPart: 'Shoulders' },
    { name: 'Rowing', bodyPart: 'Back' },
    { name: 'Running', bodyPart: 'Treadmill' },
    { name: 'Russian Twist', bodyPart: 'Abdominals' },
    { name: 'Sandbag Load', bodyPart: 'Quadriceps' },
    { name: 'Scapular Pull-Up', bodyPart: 'Traps' },
    { name: 'Scissor Kick', bodyPart: 'Abdominals' },
    { name: 'Scissors Jump', bodyPart: 'Quadriceps' },
    { name: 'Seated Band Hamstring Curl', bodyPart: 'Hamstrings' },
    { name: 'Seated Barbell Military Press', bodyPart: 'Shoulders' },
    { name: 'Seated Barbell Twist', bodyPart: 'Abdominals' },
    { name: 'Seated Bent-Over One-Arm Dumbbell Triceps Extension', bodyPart: 'Triceps' },
    { name: 'Seated Bent-Over Rear Delt Raise', bodyPart: 'Shoulders' },
    { name: 'Seated Bent-Over Two-Arm Dumbbell Triceps Extension', bodyPart: 'Triceps' },
    { name: 'Seated Biceps', bodyPart: 'Biceps' },
    { name: 'Seated Cable Rows', bodyPart: 'Middle Back' },
    { name: 'Seated Cable Shoulder Press', bodyPart: 'Shoulders' },
    { name: 'Seated Calf Raise', bodyPart: 'Calves' },
    { name: 'Seated Calf Stretch', bodyPart: 'Calves' },
    { name: 'Seated Close-Grip Concentration Barbell Curl', bodyPart: 'Biceps' },
    { name: 'Seated Dumbbell Curl', bodyPart: 'Biceps' },
    { name: 'Seated Dumbbell Inner Biceps Curl', bodyPart: 'Biceps' },
    { name: 'Seated Dumbbell Palms-Down Wrist Curl', bodyPart: 'Forearms' },
    { name: 'Seated Dumbbell Palms-Up Wrist Curl', bodyPart: 'Forearms' },
    { name: 'Seated Dumbbell Press', bodyPart: 'Shoulders' },
    { name: 'Seated Flat Bench Leg Pull-In', bodyPart: 'Abdominals' },
    { name: 'Seated Floor Hamstring Stretch', bodyPart: 'Hamstrings' },
    { name: 'Seated Front Deltoid', bodyPart: 'Shoulders' },
    { name: 'Seated Glute', bodyPart: 'Glutes' },
    { name: 'Seated Good Mornings', bodyPart: 'Lower Back' },
    { name: 'Seated Hamstring', bodyPart: 'Hamstrings' },
    { name: 'Seated Hamstring And Calf Stretch', bodyPart: 'Hamstrings' },
    { name: 'Seated Head Harness Neck Resistance', bodyPart: 'Neck' },
    { name: 'Seated Leg Curl', bodyPart: 'Hamstrings' },
    { name: 'Seated Leg Tucks', bodyPart: 'Abdominals' },
    { name: 'Seated One-Arm Cable Pulley Rows', bodyPart: 'Middle Back' },
    { name: 'Seated One-Arm Dumbbell Palms-Down Wrist Curl', bodyPart: 'Forearms' },
    { name: 'Seated One-Arm Dumbbell Palms-Up Wrist Curl', bodyPart: 'Forearms' },
    { name: 'Seated Overhead Stretch', bodyPart: 'Abdominals' },
    { name: 'Seated Palm-Up Barbell Wrist Curl', bodyPart: 'Forearms' },
    { name: 'Seated Palms-Down Barbell Wrist Curl', bodyPart: 'Forearms' },
    { name: 'Seated Side Lateral Raise', bodyPart: 'Shoulders' },
    { name: 'Seated Triceps Press', bodyPart: 'Triceps' },
    { name: 'Seated Two-Arm Palms-Up Low-Pulley Wrist Curl', bodyPart: 'Forearms' },
    { name: 'See-Saw Press (Alternating Side Press)', bodyPart: 'Shoulders' },
    { name: 'Shotgun Row', bodyPart: 'Lats' },
    { name: 'Shoulder Circles', bodyPart: 'Shoulders' },
    { name: 'Shoulder Press - With Bands', bodyPart: 'Shoulders' },
    { name: 'Shoulder Raise', bodyPart: 'Shoulders' },
    { name: 'Shoulder Stretch', bodyPart: 'Shoulders' },
    { name: 'Side Bridge', bodyPart: 'Abdominals' },
    { name: 'Side Hop-Sprint', bodyPart: 'Quadriceps' },
    { name: 'Side Jackknife', bodyPart: 'Abdominals' },
    { name: 'Side Lateral Raise', bodyPart: 'Shoulders' },
    { name: 'Side Laterals To Front Raise', bodyPart: 'Shoulders' },
    { name: 'Side Leg Raises', bodyPart: 'Adductors' },
    { name: 'Side Lying Groin Stretch', bodyPart: 'Adductors' },
    { name: 'Side Neck Stretch', bodyPart: 'Neck' },
    { name: 'Side Standing Long Jump', bodyPart: 'Quadriceps' },
    { name: 'Side To Side Box Shuffle', bodyPart: 'Quadriceps' },
    { name: 'Side To Side Chins', bodyPart: 'Lats' },
    { name: 'Side Wrist Pull', bodyPart: 'Shoulders' },
    { name: 'Side-Lying Floor Stretch', bodyPart: 'Lats' },
    { name: 'Single Dumbbell Raise', bodyPart: 'Shoulders' },
    { name: 'Single Leg Butt Kick', bodyPart: 'Quadriceps' },
    { name: 'Single Leg Glute Bridge', bodyPart: 'Glutes' },
    { name: 'Single Leg Push-Off', bodyPart: 'Quadriceps' },
    { name: 'Single-Arm Cable Crossover', bodyPart: 'Chest' },
    { name: 'Single-Arm Linear Jammer', bodyPart: 'Shoulders' },
    { name: 'Single-Arm Push-Up', bodyPart: 'Chest' },
    { name: 'Single-Cone Sprint Drill', bodyPart: 'Quadriceps' },
    { name: 'Single-Leg High Box Squat', bodyPart: 'Quadriceps' },
    { name: 'Single-Leg Hop Progression', bodyPart: 'Quadriceps' },
    { name: 'Single-Leg Lateral Hop', bodyPart: 'Quadriceps' },
    { name: 'Single-Leg Leg Extension', bodyPart: 'Quadriceps' },
    { name: 'Single-Leg Stride Jump', bodyPart: 'Quadriceps' },
    { name: 'Sit Squats', bodyPart: 'Quadriceps' },
    { name: 'Sit-Up', bodyPart: 'Abdominals' },
    { name: 'Skating', bodyPart: 'Quadriceps' },
    { name: 'Sled Drag - Harness', bodyPart: 'Quadriceps' },
    { name: 'Sled Overhead Backward Walk', bodyPart: 'Shoulders' },
    { name: 'Sled Overhead Triceps Extension', bodyPart: 'Triceps' },
    { name: 'Sled Push', bodyPart: 'Quadriceps' },
    { name: 'Sled Reverse Flye', bodyPart: 'Shoulders' },
    { name: 'Sled Row', bodyPart: 'Middle Back' },
    { name: 'Sledgehammer Swings', bodyPart: 'Abdominals' },
    { name: 'Smith Incline Shoulder Raise', bodyPart: 'Shoulders' },
    { name: 'Smith Machine Behind The Back Shrug', bodyPart: 'Traps' },
    { name: 'Smith Machine Bench Press', bodyPart: 'Chest' },
    { name: 'Smith Machine Bent Over Row', bodyPart: 'Middle Back' },
    { name: 'Smith Machine Calf Raise', bodyPart: 'Calves' },
    { name: 'Smith Machine Close-Grip Bench Press', bodyPart: 'Triceps' },
    { name: 'Smith Machine Decline Press', bodyPart: 'Chest' },
    { name: 'Smith Machine Hang Power Clean', bodyPart: 'Hamstrings' },
    { name: 'Smith Machine Hip Raise', bodyPart: 'Abdominals' },
    { name: 'Smith Machine Incline Bench Press', bodyPart: 'Chest' },
    { name: 'Smith Machine Leg Press', bodyPart: 'Quadriceps' },
    { name: 'Smith Machine One-Arm Upright Row', bodyPart: 'Shoulders' },
    { name: 'Smith Machine Overhead Shoulder Press', bodyPart: 'Shoulders' },
    { name: 'Smith Machine Pistol Squat', bodyPart: 'Quadriceps' },
    { name: 'Smith Machine Reverse Calf Raises', bodyPart: 'Calves' },
    { name: 'Smith Machine Shrug', bodyPart: 'Traps' },
    { name: 'Smith Machine Squat', bodyPart: 'Quadriceps' },
    { name: 'Smith Machine Stiff-Legged Deadlift', bodyPart: 'Hamstrings' },
    { name: 'Smith Machine Upright Row', bodyPart: 'Traps' },
    { name: 'Smith Single-Leg Split Squat', bodyPart: 'Quadriceps' },
    { name: 'Snatch', bodyPart: 'Quadriceps' },
    { name: 'Snatch Balance', bodyPart: 'Quadriceps' },
    { name: 'Snatch Deadlift', bodyPart: 'Hamstrings' },
    { name: 'Snatch From Blocks', bodyPart: 'Quadriceps' },
    { name: 'Snatch Pull', bodyPart: 'Hamstrings' },
    { name: 'Snatch Shrug', bodyPart: 'Traps' },
    { name: 'Speed Band Overhead Triceps', bodyPart: 'Triceps' },
    { name: 'Speed Band Pushdown', bodyPart: 'Triceps' },
    { name: 'Speed Box Squat', bodyPart: 'Quadriceps' },
    { name: 'Speed Squats', bodyPart: 'Quadriceps' },
    { name: 'Spell Caster', bodyPart: 'Abdominals' },
    { name: 'Spider Crawl', bodyPart: 'Abdominals' },
    { name: 'Spider Curl', bodyPart: 'Biceps' },
    { name: 'Spinal Stretch', bodyPart: 'Middle Back' },
    { name: 'Split Clean', bodyPart: 'Quadriceps' },
    { name: 'Split Jerk', bodyPart: 'Quadriceps' },
    { name: 'Split Jump', bodyPart: 'Quadriceps' },
    { name: 'Split Snatch', bodyPart: 'Hamstrings' },
    { name: 'Split Squat With Dumbbells', bodyPart: 'Quadriceps' },
    { name: 'Split Squats', bodyPart: 'Hamstrings' },
    { name: 'Squat Jerk', bodyPart: 'Quadriceps' },
    { name: 'Squat With Bands', bodyPart: 'Quadriceps' },
    { name: 'Squat With Chains', bodyPart: 'Quadriceps' },
    { name: 'Squat With Plate Movers', bodyPart: 'Quadriceps' },
    { name: 'Squats - With Bands', bodyPart: 'Quadriceps' },
    { name: 'Stairmaster', bodyPart: 'Quadriceps' },
    { name: 'Standing Alternating Dumbbell Press', bodyPart: 'Shoulders' },
    { name: 'Standing Barbell Calf Raise', bodyPart: 'Calves' },
    { name: 'Standing Barbell Press Behind Neck', bodyPart: 'Shoulders' },
    { name: 'Standing Bent-Over One-Arm Dumbbell Triceps Extension', bodyPart: 'Triceps' },
    { name: 'Standing Bent-Over Two-Arm Dumbbell Triceps Extension', bodyPart: 'Triceps' },
    { name: 'Standing Biceps Cable Curl', bodyPart: 'Biceps' },
    { name: 'Standing Biceps Stretch', bodyPart: 'Biceps' },
    { name: 'Standing Bradford Press', bodyPart: 'Shoulders' },
    { name: 'Standing Cable Chest Press', bodyPart: 'Chest' },
    { name: 'Standing Cable Lift', bodyPart: 'Abdominals' },
    { name: 'Standing Cable Wood Chop', bodyPart: 'Abdominals' },
    { name: 'Standing Calf Raises', bodyPart: 'Calves' },
    { name: 'Standing Concentration Curl', bodyPart: 'Biceps' },
    { name: 'Standing Dumbbell Calf Raise', bodyPart: 'Calves' },
    { name: 'Standing Dumbbell Press', bodyPart: 'Shoulders' },
    { name: 'Standing Dumbbell Reverse Curl', bodyPart: 'Biceps' },
    { name: 'Standing Dumbbell Straight-Arm Front Delt Raise Above Head', bodyPart: 'Shoulders' },
    { name: 'Standing Dumbbell Triceps Extension', bodyPart: 'Triceps' },
    { name: 'Standing Dumbbell Upright Row', bodyPart: 'Traps' },
    { name: 'Standing Elevated Quad Stretch', bodyPart: 'Quadriceps' },
    { name: 'Standing Front Barbell Raise Over Head', bodyPart: 'Shoulders' },
    { name: 'Standing Gastrocnemius Calf Stretch', bodyPart: 'Calves' },
    { name: 'Standing Hamstring And Calf Stretch', bodyPart: 'Hamstrings' },
    { name: 'Standing Hip Circles', bodyPart: 'Abductors' },
    { name: 'Standing Hip Flexors', bodyPart: 'Quadriceps' },
    { name: 'Standing Inner-Biceps Curl', bodyPart: 'Biceps' },
    { name: 'Standing Lateral Stretch', bodyPart: 'Abdominals' },
    { name: 'Standing Leg Curl', bodyPart: 'Hamstrings' },
    { name: 'Standing Long Jump', bodyPart: 'Quadriceps' },
    { name: 'Standing Low-Pulley Deltoid Raise', bodyPart: 'Shoulders' },
    { name: 'Standing Low-Pulley One-Arm Triceps Extension', bodyPart: 'Triceps' },
    { name: 'Standing Military Press', bodyPart: 'Shoulders' },
    { name: 'Standing Olympic Plate Hand Squeeze', bodyPart: 'Forearms' },
    { name: 'Standing One-Arm Cable Curl', bodyPart: 'Biceps' },
    { name: 'Standing One-Arm Dumbbell Curl Over Incline Bench', bodyPart: 'Biceps' },
    { name: 'Standing One-Arm Dumbbell Triceps Extension', bodyPart: 'Triceps' },
    { name: 'Standing Overhead Barbell Triceps Extension', bodyPart: 'Triceps' },
    { name: 'Standing Palm-In One-Arm Dumbbell Press', bodyPart: 'Shoulders' },
    { name: 'Standing Palms-In Dumbbell Press', bodyPart: 'Shoulders' },
    { name: 'Standing Palms-Up Barbell Behind The Back Wrist Curl', bodyPart: 'Forearms' },
    { name: 'Standing Pelvic Tilt', bodyPart: 'Lower Back' },
    { name: 'Standing Rope Crunch', bodyPart: 'Abdominals' },
    { name: 'Standing Soleus And Achilles Stretch', bodyPart: 'Calves' },
    { name: 'Standing Toe Touches', bodyPart: 'Hamstrings' },
    { name: 'Standing Towel Triceps Extension', bodyPart: 'Triceps' },
    { name: 'Standing Two-Arm Overhead Throw', bodyPart: 'Shoulders' },
    { name: 'Star Jump', bodyPart: 'Quadriceps' },
    { name: 'Step Mill', bodyPart: 'Quadriceps' },
    { name: 'Step-Up With Knee Raise', bodyPart: 'Glutes' },
    { name: 'Stiff Leg Barbell Good Morning', bodyPart: 'Lower Back' },
    { name: 'Stiff-Legged Barbell Deadlift', bodyPart: 'Hamstrings' },
    { name: 'Stiff-Legged Dumbbell Deadlift', bodyPart: 'Hamstrings' },
    { name: 'Stomach Vacuum', bodyPart: 'Abdominals' },
    { name: 'Straight Bar Bench Mid Rows', bodyPart: 'Middle Back' },
    { name: 'Straight Raises On Incline Bench', bodyPart: 'Shoulders' },
    { name: 'Straight-Arm Dumbbell Pullover', bodyPart: 'Chest' },
    { name: 'Straight-Arm Pulldown', bodyPart: 'Lats' },
    { name: 'Stride Jump Crossover', bodyPart: 'Quadriceps' },
    { name: 'Sumo Deadlift', bodyPart: 'Hamstrings' },
    { name: 'Sumo Deadlift With Bands', bodyPart: 'Hamstrings' },
    { name: 'Sumo Deadlift With Chains', bodyPart: 'Hamstrings' },
    { name: 'Superman', bodyPart: 'Lower Back' },
    { name: 'Supine Chest Throw', bodyPart: 'Triceps' },
    { name: 'Supine One-Arm Overhead Throw', bodyPart: 'Abdominals' },
    { name: 'Supine Two-Arm Overhead Throw', bodyPart: 'Abdominals' },
    { name: 'Suspended Push-Up', bodyPart: 'Chest' },
    { name: 'Suspended Reverse Crunch', bodyPart: 'Abdominals' },
    { name: 'Suspended Row', bodyPart: 'Middle Back' },
    { name: 'Suspended Split Squat', bodyPart: 'Quadriceps' },
    { name: 'T-Bar Row With Handle', bodyPart: 'Middle Back' },
    { name: 'Tate Press', bodyPart: 'Triceps' },
    { name: 'The Straddle', bodyPart: 'Hamstrings' },
    { name: 'Thigh Abductor', bodyPart: 'Abductors' },
    { name: 'Thigh Adductor', bodyPart: 'Adductors' },
    { name: 'Tire Flip', bodyPart: 'Quadriceps' },
    { name: 'Toe Touchers', bodyPart: 'Abdominals' },
    { name: 'Torso Rotation', bodyPart: 'Abdominals' },
    { name: 'Trail Running/Walking', bodyPart: 'Quadriceps' },
    { name: 'Trap Bar Deadlift', bodyPart: 'Quadriceps' },
    { name: 'Tricep Dumbbell Kickback', bodyPart: 'Triceps' },
    { name: 'Tricep Side Stretch', bodyPart: 'Triceps' },
    { name: 'Triceps Overhead Extension With Rope', bodyPart: 'Triceps' },
    { name: 'Triceps Pushdown', bodyPart: 'Triceps' },
    { name: 'Triceps Pushdown - Rope Attachment', bodyPart: 'Triceps' },
    { name: 'Triceps Pushdown - V-Bar Attachment', bodyPart: 'Triceps' },
    { name: 'Triceps Stretch', bodyPart: 'Triceps' },
    { name: 'Tuck Crunch', bodyPart: 'Abdominals' },
    { name: 'Two-Arm Dumbbell Preacher Curl', bodyPart: 'Biceps' },
    { name: 'Two-Arm Kettlebell Clean', bodyPart: 'Shoulders' },
    { name: 'Two-Arm Kettlebell Jerk', bodyPart: 'Shoulders' },
    { name: 'Two-Arm Kettlebell Military Press', bodyPart: 'Shoulders' },
    { name: 'Two-Arm Kettlebell Row', bodyPart: 'Middle Back' },
    { name: 'Underhand Cable Pulldowns', bodyPart: 'Lats' },
    { name: 'Upper Back Stretch', bodyPart: 'Middle Back' },
    { name: 'Upper Back-Leg Grab', bodyPart: 'Hamstrings' },
    { name: 'Upright Barbell Row', bodyPart: 'Shoulders' },
    { name: 'Upright Cable Row', bodyPart: 'Traps' },
    { name: 'Upright Row - With Bands', bodyPart: 'Traps' },
    { name: 'Upward Stretch', bodyPart: 'Shoulders' },
    { name: 'V-Bar Pulldown', bodyPart: 'Lats' },
    { name: 'V-Bar Pullup', bodyPart: 'Lats' },
    { name: 'Vertical Swing', bodyPart: 'Hamstrings' },
    { name: 'Walking', bodyPart: 'Treadmill' },
    { name: 'Weighted Ball Hyperextension', bodyPart: 'Lower Back' },
    { name: 'Weighted Ball Side Bend', bodyPart: 'Abdominals' },
    { name: 'Weighted Bench Dip', bodyPart: 'Triceps' },
    { name: 'Weighted Crunches', bodyPart: 'Abdominals' },
    { name: 'Weighted Jump Squat', bodyPart: 'Quadriceps' },
    { name: 'Weighted Pull Ups', bodyPart: 'Lats' },
    { name: 'Weighted Sissy Squat', bodyPart: 'Quadriceps' },
    { name: 'Weighted Sit-Ups - With Bands', bodyPart: 'Abdominals' },
    { name: 'Weighted Squat', bodyPart: 'Quadriceps' },
    { name: 'Wide Stance Barbell Squat', bodyPart: 'Quadriceps' },
    { name: 'Wide Stance Stiff Legs', bodyPart: 'Hamstrings' },
    { name: 'Wide-Grip Barbell Bench Press', bodyPart: 'Chest' },
    { name: 'Wide-Grip Decline Barbell Bench Press', bodyPart: 'Chest' },
    { name: 'Wide-Grip Decline Barbell Pullover', bodyPart: 'Chest' },
    { name: 'Wide-Grip Lat Pulldown', bodyPart: 'Lats' },
    { name: 'Wide-Grip Pulldown Behind The Neck', bodyPart: 'Lats' },
    { name: 'Wide-Grip Rear Pull-Up', bodyPart: 'Lats' },
    { name: 'Wide-Grip Standing Barbell Curl', bodyPart: 'Biceps' },
    { name: 'Wind Sprints', bodyPart: 'Abdominals' },
    { name: 'Windmills', bodyPart: 'Abductors' },
    { name: 'Wrist Circles', bodyPart: 'Forearms' },
    { name: 'Wrist Roller', bodyPart: 'Forearms' },
    { name: 'Wrist Rotations With Straight Bar', bodyPart: 'Forearms' },
    { name: 'Yoke Walk', bodyPart: 'Quadriceps' },
    { name: 'Zercher Squats', bodyPart: 'Quadriceps' },
    { name: 'Zottman Curl', bodyPart: 'Biceps' },
    { name: 'Zottman Preacher Curl', bodyPart: 'Biceps' }
]

export default exerciseData