/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_appsync_graphqlEndpoint": "https://b3vtfh3ojnej5byko6eul3h57q.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-t3sakpscpnh5vatb4u6nqmcygq",
    "aws_cognito_identity_pool_id": "ap-southeast-2:b40582b1-5d16-49d7-b763-baa736a0ee3c",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_wGW0ZRMxR",
    "aws_user_pools_web_client_id": "6i6gkrm5vfrad0vdi4fu9igh7",
    "oauth": {
        "domain": "aybowfitness-dev.auth.ap-southeast-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/profile/,https://www.aybow.com/profile/",
        "redirectSignOut": "http://localhost:3000/,https://www.aybow.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
